import type { Bracket, Country, CountyData, Region } from './regions';
import type { CountryId } from './types';

type RegionEntry = [id: string, name: string, localities?: string[]];
type CuratedCountryId = 'CN' | 'BN' | 'BS' | 'SC' | 'ZM' | 'PG';
type CompactCountryId = 'ET' | 'ZW' | 'AO' | 'MW' | 'MZ' | 'DZ' | 'IQ' | 'RU' | 'BY' | 'KG' | 'TJ'
  | 'XK' | 'AD' | 'MC' | 'BB' | 'GY' | 'TL' | 'SB' | 'VU' | 'WS' | 'TO'
  | 'CI' | 'CM' | 'ZR' | 'SZ' | 'LS' | 'GA' | 'BJ' | 'BF' | 'ML' | 'NE' | 'TD' | 'SL' | 'LR' | 'GM'
  | 'SR' | 'BZ' | 'HN' | 'NI' | 'SV' | 'HT' | 'LC' | 'AG' | 'VC' | 'GD' | 'KN' | 'DM'
  | 'MG' | 'LI' | 'SM' | 'CV' | 'PW' | 'FM' | 'MH' | 'KI' | 'NR' | 'TV' | 'CK';

// Location-only entries never invent demographic statistics or local tax rates.
function localities(regionId: string, names: string[]): CountyData[] {
  return names.map((name, index) => ({
    id: `${regionId}-LOCAL-${index + 1}`, name, seat: name, population: 0, medianIncome: 0,
    propertyTaxRate: 0, localSalesTaxRate: 0, localIncomeTaxRate: 0, labelOnly: true,
    rules: 'Location label only. No additional tax or property rate is applied automatically.',
  }));
}

function makeRegions(entries: RegionEntry[], authority: string, citation: string, salesTax: number, description: string): Region[] {
  return entries.map(([id, name, cities = []]) => ({
    id, name, code: id, cities, counties: localities(id, cities), propertyTax: 0, salesTax, flatTax: 0,
    medianIncome: 0, costOfLivingIndex: 0, referenceOnly: true, taxStructure: 'National reference; local costs entered separately',
    statuteCitation: citation, governingBody: authority, description, taxRegime: 'national',
  }));
}

function referenceCountry(config: Omit<Country, 'years' | 'regions'> & { brackets: Bracket[]; allowance?: number; locations: RegionEntry[]; salesTax: number; citation: string }): Country {
  const { brackets, allowance = 0, locations, salesTax, citation, ...country } = config;
  return {
    ...country,
    coverageNote: country.coverageNote || 'Dated employment-income reference. Localities identify your location; local taxes and assessed property bills require your own inputs.',
    years: [{ id: country.taxYear, label: `${country.taxYear} reference`, deduction: { single: allowance, joint: allowance, head: allowance }, federal: { single: brackets, joint: brackets, head: brackets } }],
    regions: makeRegions(locations, country.legalBody, citation, salesTax, country.rules),
  };
}

const annualize = (brackets: Bracket[]): Bracket[] => brackets.map(([cap, rate]) => [cap * 12, rate]);

interface CompactCountry {
  id: CompactCountryId; name: string; authority: string; currency: string; symbol: string; locale?: string;
  regionLabel: string; localityLabel: string; year: string; vat: number; allowance?: number;
  brackets: Bracket[]; rules: string; citation: string; source: [name: string, url: string];
  locations: RegionEntry[];
}

/** Dated employment-income references. Each keeps its own authority, currency, scope note and source link. */
const compactCountries: CompactCountry[] = [
  { id: 'ET', name: 'Ethiopia', authority: 'Ministry of Revenues', currency: 'ETB', symbol: 'Br', regionLabel: 'Region / city administration', localityLabel: 'City / sub-city', year: '2026', vat: 15, brackets: annualize([[600, 0], [1650, .1], [3200, .15], [5250, .2], [7800, .25], [10900, .3], [Infinity, .35]]), rules: 'Monthly employment schedule annualized for planning. Pension contributions and allowances are separate.', citation: 'Federal Income Tax Proclamation 979/2016, Schedule A', source: ['Ethiopia individual tax reference (PwC)', 'https://taxsummaries.pwc.com/ethiopia/individual/taxes-on-personal-income'], locations: [['AA', 'Addis Ababa', ['Bole', 'Kirkos', 'Yeka']], ['OR', 'Oromia', ['Adama', 'Jimma']], ['AM', 'Amhara', ['Bahir Dar', 'Gondar']], ['TG', 'Tigray', ['Mekelle']], ['SD', 'Sidama', ['Hawassa']], ['SO', 'Somali', ['Jijiga']], ['AF', 'Afar', ['Semera']], ['DD', 'Dire Dawa', ['Dire Dawa']], ['HA', 'Harari', ['Harar']], ['BG', 'Benishangul-Gumuz', ['Asosa']], ['GA', 'Gambela', ['Gambela']], ['CE', 'Central Ethiopia', ['Hosaena']], ['SW', 'South West Ethiopia', ['Bonga']], ['SE', 'South Ethiopia', ['Jinka']]] },
  { id: 'ZW', name: 'Zimbabwe', authority: 'Zimbabwe Revenue Authority (ZIMRA)', currency: 'USD', symbol: 'US$', regionLabel: 'Province', localityLabel: 'City / district', year: '2026', vat: 15, brackets: [[1200, 0], [3600, .2], [12000, .25], [24000, .3], [36000, .35], [Infinity, .4]], rules: 'USD PAYE reference bands. AIDS levy, local-currency earnings and split-currency payrolls are not modeled.', citation: 'Income Tax Act [Chapter 23:06]; ZIMRA PAYE tables', source: ['ZIMRA', 'https://www.zimra.co.zw/'], locations: [['HA', 'Harare', ['Harare', 'Chitungwiza']], ['BU', 'Bulawayo', ['Bulawayo']], ['MA', 'Manicaland', ['Mutare']], ['MC', 'Mashonaland Central', ['Bindura']], ['ME', 'Mashonaland East', ['Marondera']], ['MW', 'Mashonaland West', ['Chinhoyi']], ['MV', 'Masvingo', ['Masvingo']], ['MN', 'Matabeleland North', ['Lupane']], ['MS', 'Matabeleland South', ['Gwanda']], ['MI', 'Midlands', ['Gweru', 'Kwekwe']]] },
  { id: 'AO', name: 'Angola', authority: 'Administracao Geral Tributaria (AGT)', currency: 'AOA', symbol: 'Kz', regionLabel: 'Province', localityLabel: 'Municipality', year: '2026', vat: 14, brackets: annualize([[100000, 0], [150000, .13], [200000, .16], [300000, .18], [500000, .19], [1000000, .2], [1500000, .21], [2000000, .22], [2500000, .23], [5000000, .24], [Infinity, .25]]), rules: 'Employment income (Group A) monthly schedule annualized. Social security is separate.', citation: 'Codigo do Imposto sobre os Rendimentos do Trabalho', source: ['Angola individual tax reference (PwC)', 'https://taxsummaries.pwc.com/angola/individual/taxes-on-personal-income'], locations: [['LU', 'Luanda', ['Luanda', 'Viana', 'Cacuaco']], ['BG', 'Benguela', ['Benguela', 'Lobito']], ['HU', 'Huila', ['Lubango']], ['HO', 'Huambo', ['Huambo']], ['CA', 'Cabinda', ['Cabinda']], ['NA', 'Namibe', ['Mocamedes']], ['MA', 'Malanje', ['Malanje']], ['UI', 'Uige', ['Uige']], ['BE', 'Bengo', ['Caxito']], ['CS', 'Cuanza Sul', ['Sumbe']]] },
  { id: 'MW', name: 'Malawi', authority: 'Malawi Revenue Authority (MRA)', currency: 'MWK', symbol: 'MK', regionLabel: 'Region', localityLabel: 'City / district', year: '2026', vat: 16.5, brackets: [[1800000, 0], [6000000, .25], [30600000, .3], [Infinity, .35]], rules: 'PAYE monthly bands annualized. Pension and other statutory deductions are separate.', citation: 'Taxation Act; MRA PAYE schedule', source: ['Malawi Revenue Authority', 'https://www.mra.mw/'], locations: [['C', 'Central Region', ['Lilongwe', 'Kasungu']], ['S', 'Southern Region', ['Blantyre', 'Zomba', 'Mangochi']], ['N', 'Northern Region', ['Mzuzu', 'Karonga']]] },
  { id: 'MZ', name: 'Mozambique', authority: 'Autoridade Tributaria de Mocambique', currency: 'MZN', symbol: 'MT', regionLabel: 'Province', localityLabel: 'City / district', year: '2026', vat: 16, brackets: [[42000, .1], [168000, .15], [504000, .2], [1512000, .25], [Infinity, .32]], rules: 'IRPS annual reference for employment income. Dependants relief and INSS are not applied automatically.', citation: 'Codigo do IRPS', source: ['Mozambique individual tax reference (PwC)', 'https://taxsummaries.pwc.com/mozambique/individual/taxes-on-personal-income'], locations: [['MPM', 'Maputo City', ['Maputo']], ['MP', 'Maputo Province', ['Matola']], ['SO', 'Sofala', ['Beira']], ['NM', 'Nampula', ['Nampula']], ['ZA', 'Zambezia', ['Quelimane']], ['TE', 'Tete', ['Tete']], ['MN', 'Manica', ['Chimoio']], ['GZ', 'Gaza', ['Xai-Xai']], ['IN', 'Inhambane', ['Inhambane']], ['CD', 'Cabo Delgado', ['Pemba']], ['NI', 'Niassa', ['Lichinga']]] },
  { id: 'DZ', name: 'Algeria', authority: 'Direction Generale des Impots', currency: 'DZD', symbol: 'DA', regionLabel: 'Wilaya', localityLabel: 'Commune', year: '2026', vat: 19, brackets: [[240000, 0], [480000, .23], [960000, .27], [1920000, .3], [3840000, .33], [Infinity, .35]], rules: 'IRG salary schedule reference. Social security contributions and abatements are separate.', citation: 'Code des impots directs, IRG bareme', source: ['Algeria individual tax reference (PwC)', 'https://taxsummaries.pwc.com/algeria/individual/taxes-on-personal-income'], locations: [['16', 'Algiers', ['Algiers', 'Bab Ezzouar']], ['31', 'Oran', ['Oran']], ['25', 'Constantine', ['Constantine']], ['09', 'Blida', ['Blida']], ['19', 'Setif', ['Setif']], ['23', 'Annaba', ['Annaba']], ['06', 'Bejaia', ['Bejaia']], ['15', 'Tizi Ouzou', ['Tizi Ouzou']], ['30', 'Ouargla', ['Ouargla']], ['01', 'Adrar', ['Adrar']]] },
  { id: 'IQ', name: 'Iraq', authority: 'General Commission for Taxes', currency: 'IQD', symbol: 'ID', regionLabel: 'Governorate', localityLabel: 'City / district', year: '2026', vat: 0, brackets: [[250000, .03], [500000, .05], [1000000, .1], [Infinity, .15]], rules: 'Employment income band reference. Statutory allowances and Kurdistan Region administration differences are not modeled.', citation: 'Income Tax Law No. 113 of 1982 (as amended)', source: ['Iraq individual tax reference (PwC)', 'https://taxsummaries.pwc.com/iraq/individual/taxes-on-personal-income'], locations: [['BG', 'Baghdad', ['Baghdad']], ['BA', 'Basra', ['Basra']], ['NI', 'Nineveh', ['Mosul']], ['ER', 'Erbil', ['Erbil']], ['SU', 'Sulaymaniyah', ['Sulaymaniyah']], ['DA', 'Duhok', ['Duhok']], ['NA', 'Najaf', ['Najaf']], ['KA', 'Karbala', ['Karbala']], ['KI', 'Kirkuk', ['Kirkuk']], ['AN', 'Anbar', ['Ramadi']]] },
  { id: 'RU', name: 'Russia', authority: 'Federal Tax Service', currency: 'RUB', symbol: 'RUB', regionLabel: 'Federal subject', localityLabel: 'City / district', year: '2026', vat: 20, brackets: [[2400000, .13], [5000000, .15], [20000000, .18], [50000000, .2], [Infinity, .22]], rules: 'Resident progressive employment schedule. Non-resident treatment, deductions and special regimes are not modeled.', citation: 'Tax Code, Article 224', source: ['Russia individual tax reference (PwC)', 'https://taxsummaries.pwc.com/russian-federation/individual/taxes-on-personal-income'], locations: [['MOW', 'Moscow', ['Moscow']], ['SPE', 'Saint Petersburg', ['Saint Petersburg']], ['MOS', 'Moscow Oblast', ['Balashikha', 'Khimki']], ['SVE', 'Sverdlovsk Oblast', ['Yekaterinburg']], ['NVS', 'Novosibirsk Oblast', ['Novosibirsk']], ['TA', 'Tatarstan', ['Kazan']], ['KDA', 'Krasnodar Krai', ['Krasnodar', 'Sochi']], ['BA', 'Bashkortostan', ['Ufa']], ['CHE', 'Chelyabinsk Oblast', ['Chelyabinsk']], ['ROS', 'Rostov Oblast', ['Rostov-on-Don']], ['SAM', 'Samara Oblast', ['Samara']], ['KYA', 'Krasnoyarsk Krai', ['Krasnoyarsk']]] },
  { id: 'BY', name: 'Belarus', authority: 'Ministry of Taxes and Duties', currency: 'BYN', symbol: 'Br', regionLabel: 'Region', localityLabel: 'City / district', year: '2026', vat: 20, brackets: [[Infinity, .13]], rules: 'Flat employment income reference. Standard deductions and social contributions are separate.', citation: 'Tax Code of the Republic of Belarus', source: ['Belarus individual tax reference (PwC)', 'https://taxsummaries.pwc.com/belarus/individual/taxes-on-personal-income'], locations: [['HM', 'Minsk City', ['Minsk']], ['MI', 'Minsk Region', ['Barysaw']], ['BR', 'Brest Region', ['Brest']], ['HR', 'Grodno Region', ['Grodno']], ['VI', 'Vitebsk Region', ['Vitebsk']], ['MA', 'Mogilev Region', ['Mogilev']], ['HO', 'Gomel Region', ['Gomel']]] },
  { id: 'KG', name: 'Kyrgyzstan', authority: 'State Tax Service', currency: 'KGS', symbol: 'KGS', regionLabel: 'Region', localityLabel: 'City / district', year: '2026', vat: 12, brackets: [[Infinity, .1]], rules: 'Flat employment income reference. Social Fund contributions are separate.', citation: 'Tax Code of the Kyrgyz Republic', source: ['Kyrgyzstan individual tax reference (PwC)', 'https://taxsummaries.pwc.com/kyrgyzstan/individual/taxes-on-personal-income'], locations: [['GB', 'Bishkek', ['Bishkek']], ['GO', 'Osh City', ['Osh']], ['C', 'Chuy', ['Tokmok']], ['J', 'Jalal-Abad', ['Jalal-Abad']], ['Y', 'Issyk-Kul', ['Karakol']], ['N', 'Naryn', ['Naryn']], ['T', 'Talas', ['Talas']], ['B', 'Batken', ['Batken']]] },
  { id: 'TJ', name: 'Tajikistan', authority: 'Tax Committee', currency: 'TJS', symbol: 'SM', regionLabel: 'Region', localityLabel: 'City / district', year: '2026', vat: 14, brackets: [[Infinity, .12]], rules: 'Employment income reference rate. Social tax and non-resident treatment are separate.', citation: 'Tax Code of the Republic of Tajikistan', source: ['Tajikistan individual tax reference (PwC)', 'https://taxsummaries.pwc.com/tajikistan/individual/taxes-on-personal-income'], locations: [['DU', 'Dushanbe', ['Dushanbe']], ['SU', 'Sughd', ['Khujand']], ['KT', 'Khatlon', ['Bokhtar', 'Kulob']], ['GB', 'Gorno-Badakhshan', ['Khorugh']], ['RA', 'Districts of Republican Subordination', ['Vahdat']]] },
  { id: 'XK', name: 'Kosovo', authority: 'Tax Administration of Kosovo', currency: 'EUR', symbol: 'EUR', regionLabel: 'District', localityLabel: 'Municipality', year: '2026', vat: 18, brackets: [[960, 0], [3000, .04], [5400, .08], [Infinity, .1]], rules: 'Annual employment income bands. Pension contributions are separate.', citation: 'Law on Personal Income Tax', source: ['Kosovo individual tax reference (PwC)', 'https://taxsummaries.pwc.com/kosovo/individual/taxes-on-personal-income'], locations: [['PR', 'Pristina', ['Pristina']], ['PZ', 'Prizren', ['Prizren']], ['PE', 'Peja', ['Peja']], ['GJ', 'Gjakova', ['Gjakova']], ['MI', 'Mitrovica', ['Mitrovica']], ['FE', 'Ferizaj', ['Ferizaj']], ['GL', 'Gjilan', ['Gjilan']]] },
  { id: 'AD', name: 'Andorra', authority: 'Departament de Tributs i de Fronteres', currency: 'EUR', symbol: 'EUR', regionLabel: 'Parish', localityLabel: 'Town', year: '2026', vat: 4.5, brackets: [[24000, 0], [40000, .05], [Infinity, .1]], rules: 'Resident IRPF reference bands. Family, housing and pension reductions are not applied automatically.', citation: 'Llei 5/2014 de l impost sobre la renda de les persones fisiques', source: ['Andorra individual tax reference (PwC)', 'https://taxsummaries.pwc.com/andorra/individual/taxes-on-personal-income'], locations: [['AL', 'Andorra la Vella', ['Andorra la Vella']], ['EE', 'Escaldes-Engordany', ['Escaldes-Engordany']], ['EN', 'Encamp', ['Encamp']], ['LM', 'La Massana', ['La Massana']], ['OR', 'Ordino', ['Ordino']], ['SJ', 'Sant Julia de Loria', ['Sant Julia de Loria']], ['CA', 'Canillo', ['Canillo']]] },
  { id: 'MC', name: 'Monaco', authority: 'Direction des Services Fiscaux', currency: 'EUR', symbol: 'EUR', regionLabel: 'Ward', localityLabel: 'Quarter', year: '2026', vat: 20, brackets: [[Infinity, 0]], rules: 'No personal income tax on employment for residents. French nationals may remain taxable in France under the 1963 convention.', citation: 'Franco-Monegasque Convention of 1963', source: ['Monaco individual tax reference (PwC)', 'https://taxsummaries.pwc.com/monaco/individual/taxes-on-personal-income'], locations: [['MO', 'Monaco-Ville', ['Monaco-Ville']], ['MC', 'Monte-Carlo', ['Monte-Carlo']], ['CO', 'La Condamine', ['La Condamine']], ['FO', 'Fontvieille', ['Fontvieille']]] },
  { id: 'BB', name: 'Barbados', authority: 'Barbados Revenue Authority', currency: 'BBD', symbol: 'Bds$', regionLabel: 'Parish', localityLabel: 'Town / district', year: '2026', vat: 17.5, allowance: 25000, brackets: [[50000, .125], [Infinity, .285]], rules: 'Personal allowance plus two employment bands. NIS contributions are separate.', citation: 'Income Tax Act, Cap. 73', source: ['Barbados individual tax reference (PwC)', 'https://taxsummaries.pwc.com/barbados/individual/taxes-on-personal-income'], locations: [['01', 'Saint Michael', ['Bridgetown']], ['02', 'Christ Church', ['Oistins']], ['03', 'Saint James', ['Holetown']], ['04', 'Saint Philip', ['Six Cross Roads']], ['05', 'Saint George', ['Bulkeley']], ['06', 'Saint Peter', ['Speightstown']], ['07', 'Saint Lucy', ['Crab Hill']], ['08', 'Saint Thomas', ['Hillaby']], ['09', 'Saint John', ['Four Roads']], ['10', 'Saint Joseph', ['Bathsheba']], ['11', 'Saint Andrew', ['Greenland']]] },
  { id: 'GY', name: 'Guyana', authority: 'Guyana Revenue Authority', currency: 'GYD', symbol: 'G$', regionLabel: 'Region', localityLabel: 'Town / village', year: '2026', vat: 14, allowance: 1020000, brackets: [[2400000, .25], [Infinity, .35]], rules: 'Personal allowance then two PAYE bands. NIS contributions and dependant allowances are separate.', citation: 'Income Tax Act, Cap. 81:01', source: ['Guyana individual tax reference (PwC)', 'https://taxsummaries.pwc.com/guyana/individual/taxes-on-personal-income'], locations: [['04', 'Demerara-Mahaica', ['Georgetown']], ['06', 'East Berbice-Corentyne', ['New Amsterdam']], ['03', 'Essequibo Islands-West Demerara', ['Vreed-en-Hoop']], ['05', 'Mahaica-Berbice', ['Fort Wellington']], ['02', 'Pomeroon-Supenaam', ['Anna Regina']], ['10', 'Upper Demerara-Berbice', ['Linden']], ['07', 'Cuyuni-Mazaruni', ['Bartica']], ['01', 'Barima-Waini', ['Mabaruma']], ['08', 'Potaro-Siparuni', ['Mahdia']], ['09', 'Upper Takutu-Upper Essequibo', ['Lethem']]] },
  { id: 'TL', name: 'Timor-Leste', authority: 'Autoridade Tributaria', currency: 'USD', symbol: 'US$', regionLabel: 'Municipality', localityLabel: 'Administrative post', year: '2026', vat: 0, brackets: [[6000, 0], [Infinity, .1]], rules: 'Resident wage income reference. Non-resident wage withholding differs and is not modeled.', citation: 'Taxes and Duties Act 2008', source: ['Timor-Leste individual tax reference (PwC)', 'https://taxsummaries.pwc.com/timor-leste/individual/taxes-on-personal-income'], locations: [['DI', 'Dili', ['Dili']], ['BA', 'Baucau', ['Baucau']], ['BO', 'Bobonaro', ['Maliana']], ['ER', 'Ermera', ['Gleno']], ['CO', 'Covalima', ['Suai']], ['LA', 'Lautem', ['Lospalos']], ['MT', 'Manatuto', ['Manatuto']], ['OE', 'Oecusse', ['Pante Macassar']]] },
  { id: 'SB', name: 'Solomon Islands', authority: 'Inland Revenue Division', currency: 'SBD', symbol: 'SI$', regionLabel: 'Province', localityLabel: 'Town / ward', year: '2026', vat: 15, brackets: [[30080, 0], [60000, .11], [90000, .23], [Infinity, .35]], rules: 'PAYE reference bands for resident employees. NPF contributions are separate.', citation: 'Income Tax Act [Cap. 123]', source: ['Solomon Islands Inland Revenue Division', 'https://www.ird.gov.sb/'], locations: [['CT', 'Honiara Capital Territory', ['Honiara']], ['GU', 'Guadalcanal', ['Tulagi']], ['ML', 'Malaita', ['Auki']], ['WE', 'Western', ['Gizo', 'Noro']], ['IS', 'Isabel', ['Buala']], ['MK', 'Makira-Ulawa', ['Kirakira']], ['CH', 'Choiseul', ['Taro Island']], ['TE', 'Temotu', ['Lata']], ['CE', 'Central Islands', ['Tulagi']], ['RB', 'Rennell and Bellona', ['Tigoa']]] },
  { id: 'VU', name: 'Vanuatu', authority: 'Department of Customs and Inland Revenue', currency: 'VUV', symbol: 'VT', regionLabel: 'Province', localityLabel: 'Town / area', year: '2026', vat: 15, brackets: [[Infinity, 0]], rules: 'No personal income tax on wages. VNPF contributions and VAT are separate.', citation: 'No personal income tax on employment income', source: ['Vanuatu Customs and Inland Revenue', 'https://customsinlandrevenue.gov.vu/'], locations: [['SM', 'Shefa', ['Port Vila']], ['SN', 'Sanma', ['Luganville']], ['TF', 'Tafea', ['Isangel']], ['ML', 'Malampa', ['Lakatoro']], ['PM', 'Penama', ['Saratamata']], ['TB', 'Torba', ['Sola']]] },
  { id: 'WS', name: 'Samoa', authority: 'Ministry for Customs and Revenue', currency: 'WST', symbol: 'WS$', regionLabel: 'District', localityLabel: 'Village / area', year: '2026', vat: 15, brackets: [[15000, 0], [25000, .2], [Infinity, .27]], rules: 'PAYE reference bands for resident employees. SNPF contributions are separate.', citation: 'Income Tax Act 2012', source: ['Samoa Ministry for Customs and Revenue', 'https://www.revenue.gov.ws/'], locations: [['TU', 'Tuamasaga', ['Apia']], ['AA', 'Aana', ['Leulumoega']], ['AI', 'Aiga-i-le-Tai', ['Mulifanua']], ['AT', 'Atua', ['Lufilufi']], ['VF', 'Vaisigano', ['Asau']], ['GI', 'Gagaifomauga', ['Safotu']], ['FA', 'Faasaleleaga', ['Safotulafai']], ['SA', 'Satupaitea', ['Satupaitea']]] },
  { id: 'TO', name: 'Tonga', authority: 'Ministry of Revenue and Customs', currency: 'TOP', symbol: 'T$', regionLabel: 'Division', localityLabel: 'Town / village', year: '2026', vat: 15, brackets: [[10000, 0], [Infinity, .25]], rules: 'Resident PAYE reference bands. Retirement fund contributions are separate.', citation: 'Income Tax Act 2007', source: ['Tonga Ministry of Revenue and Customs', 'https://www.revenue.gov.to/'], locations: [['TT', 'Tongatapu', ['Nukualofa']], ['VV', 'Vavau', ['Neiafu']], ['HP', 'Haapai', ['Pangai']], ['EU', 'Eua', ['Ohonua']], ['NI', 'Niuas', ['Hihifo']]] },

  { id: 'CI', name: 'Cote d Ivoire', authority: 'Direction Generale des Impots', currency: 'XOF', symbol: 'CFA', regionLabel: 'District', localityLabel: 'City / department', year: '2026', vat: 18, brackets: annualize([[75000, 0], [240000, .16], [800000, .21], [2400000, .24], [8000000, .28], [Infinity, .32]]), rules: 'Unified salary tax (ITS) monthly schedule annualized. Family quotient relief and CNPS are separate.', citation: 'Code general des impots, ITS', source: ['Cote d Ivoire individual tax reference (PwC)', 'https://taxsummaries.pwc.com/ivory-coast/individual/taxes-on-personal-income'], locations: [['AB', 'Abidjan', ['Abidjan', 'Cocody', 'Yopougon']], ['YA', 'Yamoussoukro', ['Yamoussoukro']], ['BS', 'Bas-Sassandra', ['San-Pedro']], ['VB', 'Vallee du Bandama', ['Bouake']], ['SC', 'Sassandra-Marahoue', ['Daloa']], ['MO', 'Montagnes', ['Man']], ['CO', 'Comoe', ['Abengourou']], ['LC', 'Lacs', ['Dimbokro']], ['SM', 'Savanes', ['Korhogo']], ['ZA', 'Zanzan', ['Bondoukou']]] },
  { id: 'CM', name: 'Cameroon', authority: 'Direction Generale des Impots', currency: 'XAF', symbol: 'FCFA', regionLabel: 'Region', localityLabel: 'City / division', year: '2026', vat: 19.25, brackets: [[2000000, .11], [3000000, .165], [5000000, .275], [Infinity, .385]], rules: 'Salary tax bands including additional council tax loading. CNPS contributions are separate.', citation: 'Code general des impots du Cameroun', source: ['Cameroon individual tax reference (PwC)', 'https://taxsummaries.pwc.com/republic-of-cameroon/individual/taxes-on-personal-income'], locations: [['LT', 'Littoral', ['Douala']], ['CE', 'Centre', ['Yaounde']], ['OU', 'West', ['Bafoussam']], ['NW', 'North-West', ['Bamenda']], ['SW', 'South-West', ['Buea', 'Limbe']], ['NO', 'North', ['Garoua']], ['EN', 'Far North', ['Maroua']], ['AD', 'Adamawa', ['Ngaoundere']], ['ES', 'East', ['Bertoua']], ['SU', 'South', ['Ebolowa']]] },
  { id: 'ZR', name: 'DR Congo', authority: 'Direction Generale des Impots (DGI)', currency: 'CDF', symbol: 'FC', regionLabel: 'Province', localityLabel: 'City / territory', year: '2026', vat: 16, brackets: [[1944000, .03], [21600000, .15], [43200000, .3], [Infinity, .4]], rules: 'IPR employment schedule reference, capped at 30% of gross in practice. INSS contributions are separate.', citation: 'Impot professionnel sur les remunerations (IPR)', source: ['DR Congo individual tax reference (PwC)', 'https://taxsummaries.pwc.com/democratic-republic-of-the-congo/individual/taxes-on-personal-income'], locations: [['KN', 'Kinshasa', ['Kinshasa']], ['HK', 'Haut-Katanga', ['Lubumbashi']], ['NK', 'North Kivu', ['Goma']], ['SK', 'South Kivu', ['Bukavu']], ['KC', 'Kasai-Central', ['Kananga']], ['KG', 'Kongo-Central', ['Matadi']], ['TS', 'Tshopo', ['Kisangani']], ['LU', 'Lualaba', ['Kolwezi']], ['IT', 'Ituri', ['Bunia']], ['EQ', 'Equateur', ['Mbandaka']]] },
  { id: 'SZ', name: 'Eswatini', authority: 'Eswatini Revenue Service', currency: 'SZL', symbol: 'E', regionLabel: 'Region', localityLabel: 'City / inkhundla', year: '2026', vat: 15, brackets: [[100000, .2], [150000, .25], [200000, .3], [Infinity, .33]], rules: 'PAYE bands with a personal rebate applied separately. Provident fund contributions are not modeled.', citation: 'Income Tax Order 1975 (as amended)', source: ['Eswatini Revenue Service', 'https://www.ers.org.sz/'], locations: [['HH', 'Hhohho', ['Mbabane']], ['MA', 'Manzini', ['Manzini']], ['LU', 'Lubombo', ['Siteki']], ['SH', 'Shiselweni', ['Nhlangano']]] },
  { id: 'LS', name: 'Lesotho', authority: 'Revenue Services Lesotho', currency: 'LSL', symbol: 'M', regionLabel: 'District', localityLabel: 'Town / community', year: '2026', vat: 15, brackets: [[69120, .2], [Infinity, .3]], rules: 'Two PAYE bands with a personal tax credit applied separately.', citation: 'Income Tax Act 1993', source: ['Revenue Services Lesotho', 'https://www.rsl.org.ls/'], locations: [['MS', 'Maseru', ['Maseru']], ['LE', 'Leribe', ['Hlotse']], ['BB', 'Berea', ['Teyateyaneng']], ['MF', 'Mafeteng', ['Mafeteng']], ['MH', 'Mohales Hoek', ['Mohales Hoek']], ['QN', 'Qachas Nek', ['Qachas Nek']], ['BT', 'Butha-Buthe', ['Butha-Buthe']], ['MK', 'Mokhotlong', ['Mokhotlong']], ['QT', 'Quthing', ['Quthing']], ['TT', 'Thaba-Tseka', ['Thaba-Tseka']]] },
  { id: 'GA', name: 'Gabon', authority: 'Direction Generale des Impots', currency: 'XAF', symbol: 'FCFA', regionLabel: 'Province', localityLabel: 'City / department', year: '2026', vat: 18, brackets: [[1500000, 0], [1920000, .05], [2700000, .1], [3600000, .15], [5160000, .2], [7500000, .25], [11000000, .3], [Infinity, .35]], rules: 'IRPP annual schedule for employment income. Family quotient and CNSS are separate.', citation: 'Code general des impots du Gabon', source: ['Gabon individual tax reference (PwC)', 'https://taxsummaries.pwc.com/gabon/individual/taxes-on-personal-income'], locations: [['ES', 'Estuaire', ['Libreville']], ['HO', 'Haut-Ogooue', ['Franceville']], ['OM', 'Ogooue-Maritime', ['Port-Gentil']], ['WN', 'Woleu-Ntem', ['Oyem']], ['MO', 'Moyen-Ogooue', ['Lambarene']], ['NG', 'Ngounie', ['Mouila']], ['NY', 'Nyanga', ['Tchibanga']], ['OI', 'Ogooue-Ivindo', ['Makokou']], ['OL', 'Ogooue-Lolo', ['Koulamoutou']]] },
  { id: 'BJ', name: 'Benin', authority: 'Direction Generale des Impots', currency: 'XOF', symbol: 'CFA', regionLabel: 'Department', localityLabel: 'City / commune', year: '2026', vat: 18, brackets: annualize([[60000, 0], [150000, .1], [250000, .15], [500000, .19], [Infinity, .3]]), rules: 'ITS monthly salary schedule annualized. Social security is separate.', citation: 'Code general des impots du Benin', source: ['Benin individual tax reference (PwC)', 'https://taxsummaries.pwc.com/benin/individual/taxes-on-personal-income'], locations: [['LI', 'Littoral', ['Cotonou']], ['AQ', 'Atlantique', ['Abomey-Calavi']], ['OU', 'Oueme', ['Porto-Novo']], ['BO', 'Borgou', ['Parakou']], ['ZO', 'Zou', ['Abomey']], ['AK', 'Atacora', ['Natitingou']], ['MO', 'Mono', ['Lokossa']], ['CO', 'Collines', ['Save']], ['DO', 'Donga', ['Djougou']], ['AL', 'Alibori', ['Kandi']]] },
  { id: 'BF', name: 'Burkina Faso', authority: 'Direction Generale des Impots', currency: 'XOF', symbol: 'CFA', regionLabel: 'Region', localityLabel: 'City / province', year: '2026', vat: 18, brackets: annualize([[30000, 0], [50000, .129], [80000, .159], [120000, .189], [170000, .219], [250000, .249], [Infinity, .279]]), rules: 'IUTS monthly salary schedule annualized. Family allowances and CNSS are separate.', citation: 'Impot unique sur les traitements et salaires (IUTS)', source: ['Burkina Faso individual tax reference (PwC)', 'https://taxsummaries.pwc.com/burkina-faso/individual/taxes-on-personal-income'], locations: [['KAD', 'Centre', ['Ouagadougou']], ['HBS', 'Hauts-Bassins', ['Bobo-Dioulasso']], ['NOR', 'Nord', ['Ouahigouya']], ['EST', 'Est', ['Fada Ngourma']], ['SAH', 'Sahel', ['Dori']], ['BMH', 'Boucle du Mouhoun', ['Dedougou']], ['CEN', 'Centre-Est', ['Tenkodogo']], ['CAS', 'Cascades', ['Banfora']], ['PCL', 'Plateau-Central', ['Ziniare']], ['SUD', 'Sud-Ouest', ['Gaoua']]] },
  { id: 'ML', name: 'Mali', authority: 'Direction Generale des Impots', currency: 'XOF', symbol: 'CFA', regionLabel: 'Region', localityLabel: 'City / cercle', year: '2026', vat: 18, brackets: annualize([[175000, 0], [600000, .05], [1200000, .13], [1800000, .2], [2400000, .28], [3500000, .34], [Infinity, .4]]), rules: 'ITS schedule reference. Family deductions and INPS are separate.', citation: 'Code general des impots du Mali', source: ['Mali individual tax reference (PwC)', 'https://taxsummaries.pwc.com/mali/individual/taxes-on-personal-income'], locations: [['BKO', 'Bamako', ['Bamako']], ['SIK', 'Sikasso', ['Sikasso']], ['SEG', 'Segou', ['Segou']], ['MOP', 'Mopti', ['Mopti']], ['KAY', 'Kayes', ['Kayes']], ['KOU', 'Koulikoro', ['Koulikoro']], ['TOM', 'Tombouctou', ['Tombouctou']], ['GAO', 'Gao', ['Gao']], ['KID', 'Kidal', ['Kidal']]] },
  { id: 'NE', name: 'Niger', authority: 'Direction Generale des Impots', currency: 'XOF', symbol: 'CFA', regionLabel: 'Region', localityLabel: 'City / department', year: '2026', vat: 19, brackets: annualize([[25000, 0], [50000, .02], [100000, .06], [150000, .13], [300000, .25], [400000, .3], [700000, .32], [1000000, .34], [Infinity, .35]]), rules: 'ITS monthly salary schedule annualized. CNSS contributions are separate.', citation: 'Code general des impots du Niger', source: ['Niger individual tax reference (PwC)', 'https://taxsummaries.pwc.com/niger/individual/taxes-on-personal-income'], locations: [['NI', 'Niamey', ['Niamey']], ['ZI', 'Zinder', ['Zinder']], ['MA', 'Maradi', ['Maradi']], ['TA', 'Tahoua', ['Tahoua']], ['DO', 'Dosso', ['Dosso']], ['TI', 'Tillaberi', ['Tillaberi']], ['AG', 'Agadez', ['Agadez']], ['DI', 'Diffa', ['Diffa']]] },
  { id: 'TD', name: 'Chad', authority: 'Direction Generale des Services des Impots', currency: 'XAF', symbol: 'FCFA', regionLabel: 'Province', localityLabel: 'City / department', year: '2026', vat: 18, brackets: [[800000, 0], [2500000, .1], [7500000, .2], [Infinity, .3]], rules: 'IRPP employment schedule reference. CNPS contributions are separate.', citation: 'Code general des impots du Tchad', source: ['Chad individual tax reference (PwC)', 'https://taxsummaries.pwc.com/chad/individual/taxes-on-personal-income'], locations: [['ND', 'NDjamena', ['NDjamena']], ['LC', 'Logone Occidental', ['Moundou']], ['MC', 'Moyen-Chari', ['Sarh']], ['OD', 'Ouaddai', ['Abeche']], ['MK', 'Mayo-Kebbi Est', ['Bongor']], ['CB', 'Chari-Baguirmi', ['Massenya']], ['KA', 'Kanem', ['Mao']], ['BE', 'Borkou', ['Faya-Largeau']]] },
  { id: 'SL', name: 'Sierra Leone', authority: 'National Revenue Authority', currency: 'SLE', symbol: 'Le', regionLabel: 'Province / area', localityLabel: 'City / district', year: '2026', vat: 15, brackets: annualize([[600, 0], [1200, .15], [1800, .2], [2400, .25], [Infinity, .3]]), rules: 'PAYE monthly bands annualized in redenominated leones. NASSIT contributions are separate.', citation: 'Income Tax Act 2000 (as amended)', source: ['National Revenue Authority Sierra Leone', 'https://www.nra.gov.sl/'], locations: [['W', 'Western Area', ['Freetown']], ['N', 'Northern Province', ['Makeni']], ['S', 'Southern Province', ['Bo']], ['E', 'Eastern Province', ['Kenema']], ['NW', 'North West Province', ['Port Loko']]] },
  { id: 'LR', name: 'Liberia', authority: 'Liberia Revenue Authority', currency: 'LRD', symbol: 'L$', regionLabel: 'County', localityLabel: 'City / district', year: '2026', vat: 10, brackets: [[70000, 0], [200000, .05], [800000, .15], [Infinity, .25]], rules: 'Annual PAYE bands reference. NASSCORP contributions are separate.', citation: 'Liberia Revenue Code', source: ['Liberia Revenue Authority', 'https://www.lra.gov.lr/'], locations: [['MO', 'Montserrado', ['Monrovia']], ['NI', 'Nimba', ['Ganta']], ['BG', 'Bong', ['Gbarnga']], ['MG', 'Margibi', ['Kakata']], ['GB', 'Grand Bassa', ['Buchanan']], ['LO', 'Lofa', ['Voinjama']], ['GC', 'Grand Cape Mount', ['Robertsport']], ['SI', 'Sinoe', ['Greenville']]] },
  { id: 'GM', name: 'Gambia', authority: 'Gambia Revenue Authority', currency: 'GMD', symbol: 'D', regionLabel: 'Region', localityLabel: 'City / district', year: '2026', vat: 15, brackets: [[24000, 0], [34000, .05], [44000, .1], [54000, .15], [64000, .2], [Infinity, .25]], rules: 'Annual PAYE bands reference. Social security contributions are separate.', citation: 'Income and Value Added Tax Act 2012', source: ['Gambia Revenue Authority', 'https://www.gra.gm/'], locations: [['B', 'Banjul', ['Banjul']], ['M', 'West Coast', ['Brikama']], ['L', 'Lower River', ['Mansa Konko']], ['N', 'North Bank', ['Kerewan']], ['C', 'Central River', ['Janjanbureh']], ['U', 'Upper River', ['Basse Santa Su']]] },
  { id: 'SR', name: 'Suriname', authority: 'Belastingdienst Suriname', currency: 'SRD', symbol: 'SRD', regionLabel: 'District', localityLabel: 'City / resort', year: '2026', vat: 10, brackets: [[108000, 0], [150000, .08], [183000, .18], [Infinity, .38]], rules: 'Wage tax reference with a tax-free allowance. Bands have been revised frequently; confirm the current schedule before use.', citation: 'Wet Loonbelasting', source: ['Suriname individual tax reference (PwC)', 'https://taxsummaries.pwc.com/suriname/individual/taxes-on-personal-income'], locations: [['PM', 'Paramaribo', ['Paramaribo']], ['WA', 'Wanica', ['Lelydorp']], ['NI', 'Nickerie', ['Nieuw Nickerie']], ['CM', 'Commewijne', ['Nieuw Amsterdam']], ['SA', 'Saramacca', ['Groningen']], ['PR', 'Para', ['Onverwacht']], ['MA', 'Marowijne', ['Albina']], ['BR', 'Brokopondo', ['Brokopondo']]] },
  { id: 'BZ', name: 'Belize', authority: 'Belize Tax Service', currency: 'BZD', symbol: 'BZ$', regionLabel: 'District', localityLabel: 'Town / village', year: '2026', vat: 12.5, allowance: 26000, brackets: [[Infinity, .25]], rules: 'Flat 25% on chargeable income above the basic deduction. Social security is separate.', citation: 'Income and Business Tax Act', source: ['Belize Tax Service', 'https://www.incometaxbelize.gov.bz/'], locations: [['BZ', 'Belize District', ['Belize City']], ['CY', 'Cayo', ['Belmopan', 'San Ignacio']], ['OW', 'Orange Walk', ['Orange Walk Town']], ['CZL', 'Corozal', ['Corozal Town']], ['SC', 'Stann Creek', ['Dangriga']], ['TOL', 'Toledo', ['Punta Gorda']]] },
  { id: 'HN', name: 'Honduras', authority: 'Servicio de Administracion de Rentas (SAR)', currency: 'HNL', symbol: 'L', regionLabel: 'Department', localityLabel: 'City / municipality', year: '2026', vat: 15, brackets: [[199039.47, 0], [303499.9, .15], [705813.76, .2], [Infinity, .25]], rules: 'Annual employment income schedule. Social security and educational contributions are separate.', citation: 'Ley del Impuesto sobre la Renta', source: ['Honduras individual tax reference (PwC)', 'https://taxsummaries.pwc.com/honduras/individual/taxes-on-personal-income'], locations: [['FM', 'Francisco Morazan', ['Tegucigalpa']], ['CR', 'Cortes', ['San Pedro Sula']], ['AT', 'Atlantida', ['La Ceiba']], ['YO', 'Yoro', ['El Progreso']], ['CH', 'Choluteca', ['Choluteca']], ['CM', 'Comayagua', ['Comayagua']], ['CP', 'Copan', ['Santa Rosa de Copan']], ['OL', 'Olancho', ['Juticalpa']]] },
  { id: 'NI', name: 'Nicaragua', authority: 'Direccion General de Ingresos', currency: 'NIO', symbol: 'C$', regionLabel: 'Department', localityLabel: 'City / municipality', year: '2026', vat: 15, brackets: [[100000, 0], [200000, .15], [350000, .2], [500000, .25], [Infinity, .3]], rules: 'Annual employment income schedule. INSS contributions are separate.', citation: 'Ley de Concertacion Tributaria', source: ['Nicaragua individual tax reference (PwC)', 'https://taxsummaries.pwc.com/nicaragua/individual/taxes-on-personal-income'], locations: [['MN', 'Managua', ['Managua']], ['LE', 'Leon', ['Leon']], ['MS', 'Masaya', ['Masaya']], ['CI', 'Chinandega', ['Chinandega']], ['MT', 'Matagalpa', ['Matagalpa']], ['GR', 'Granada', ['Granada']], ['ES', 'Esteli', ['Esteli']], ['RI', 'Rivas', ['Rivas']]] },
  { id: 'SV', name: 'El Salvador', authority: 'Ministerio de Hacienda', currency: 'USD', symbol: 'US$', regionLabel: 'Department', localityLabel: 'City / municipality', year: '2026', vat: 13, brackets: [[4064, 0], [9142.86, .1], [22857.14, .2], [Infinity, .3]], rules: 'Annual employment income schedule with fixed band credits applied separately. ISSS and AFP are separate.', citation: 'Ley de Impuesto sobre la Renta', source: ['El Salvador individual tax reference (PwC)', 'https://taxsummaries.pwc.com/el-salvador/individual/taxes-on-personal-income'], locations: [['SS', 'San Salvador', ['San Salvador', 'Soyapango']], ['LL', 'La Libertad', ['Santa Tecla']], ['SA', 'Santa Ana', ['Santa Ana']], ['SM', 'San Miguel', ['San Miguel']], ['SO', 'Sonsonate', ['Sonsonate']], ['LP', 'La Paz', ['Zacatecoluca']], ['US', 'Usulutan', ['Usulutan']], ['AH', 'Ahuachapan', ['Ahuachapan']]] },
  { id: 'HT', name: 'Haiti', authority: 'Direction Generale des Impots', currency: 'HTG', symbol: 'G', regionLabel: 'Department', localityLabel: 'City / commune', year: '2026', vat: 10, brackets: [[240000, 0], [480000, .1], [1000000, .15], [1500000, .25], [Infinity, .3]], rules: 'Annual employment income reference. ONA and OFATMA contributions are separate.', citation: 'Code general des impots d Haiti', source: ['Direction Generale des Impots Haiti', 'https://www.dgi.gouv.ht/'], locations: [['OU', 'Ouest', ['Port-au-Prince', 'Delmas']], ['ND', 'Nord', ['Cap-Haitien']], ['AR', 'Artibonite', ['Gonaives']], ['SD', 'Sud', ['Les Cayes']], ['CE', 'Centre', ['Hinche']], ['NE', 'Nord-Est', ['Fort-Liberte']], ['GA', 'Grande-Anse', ['Jeremie']], ['NI', 'Nippes', ['Miragoane']]] },
  { id: 'LC', name: 'Saint Lucia', authority: 'Inland Revenue Department', currency: 'XCD', symbol: 'EC$', regionLabel: 'District', localityLabel: 'Town / quarter', year: '2026', vat: 12.5, allowance: 25000, brackets: [[10000, .1], [20000, .15], [30000, .2], [Infinity, .3]], rules: 'Personal allowance then progressive bands. NIC contributions are separate.', citation: 'Income Tax Act, Cap. 15.02', source: ['Saint Lucia Inland Revenue Department', 'https://www.irdstlucia.gov.lc/'], locations: [['CA', 'Castries', ['Castries']], ['GR', 'Gros Islet', ['Gros Islet', 'Rodney Bay']], ['VF', 'Vieux Fort', ['Vieux Fort']], ['SO', 'Soufriere', ['Soufriere']], ['MI', 'Micoud', ['Micoud']], ['DE', 'Dennery', ['Dennery']]] },
  { id: 'AG', name: 'Antigua and Barbuda', authority: 'Inland Revenue Department', currency: 'XCD', symbol: 'EC$', regionLabel: 'Parish', localityLabel: 'Town / village', year: '2026', vat: 17, brackets: [[Infinity, 0]], rules: 'Personal income tax on employment was repealed in 2016. Social security and education levy remain separate.', citation: 'Personal Income Tax (Repeal) Act 2016', source: ['Antigua and Barbuda Inland Revenue Department', 'https://ird.gov.ag/'], locations: [['SJ', 'Saint John', ['St. Johns']], ['SG', 'Saint George', ['Piggotts']], ['SM', 'Saint Mary', ['Bolans']], ['SP', 'Saint Paul', ['English Harbour']], ['SPE', 'Saint Peter', ['Parham']], ['SPH', 'Saint Philip', ['Willikies']], ['BA', 'Barbuda', ['Codrington']]] },
  { id: 'VC', name: 'Saint Vincent and the Grenadines', authority: 'Inland Revenue Department', currency: 'XCD', symbol: 'EC$', regionLabel: 'Parish', localityLabel: 'Town / district', year: '2026', vat: 16, allowance: 22000, brackets: [[15000, .1], [30000, .2], [Infinity, .28]], rules: 'Personal allowance then progressive bands on cumulative thresholds. NIS contributions are separate.', citation: 'Income Tax Act, Cap. 435', source: ['SVG Inland Revenue Department', 'https://www.ird.gov.vc/'], locations: [['SG', 'Saint George', ['Kingstown']], ['SA', 'Saint Andrew', ['Layou']], ['SD', 'Saint David', ['Chateaubelair']], ['SP', 'Saint Patrick', ['Barrouallie']], ['CH', 'Charlotte', ['Georgetown']], ['GR', 'Grenadines', ['Port Elizabeth']]] },
  { id: 'GD', name: 'Grenada', authority: 'Inland Revenue Division', currency: 'XCD', symbol: 'EC$', regionLabel: 'Parish', localityLabel: 'Town / district', year: '2026', vat: 15, allowance: 36000, brackets: [[24000, .1], [Infinity, .3]], rules: 'Personal allowance then two bands. NIS contributions are separate.', citation: 'Income Tax Act, Cap. 149', source: ['Grenada Inland Revenue Division', 'https://www.ird.gd/'], locations: [['SG', 'Saint George', ['St. Georges']], ['SD', 'Saint David', ['St. Davids']], ['SA', 'Saint Andrew', ['Grenville']], ['SP', 'Saint Patrick', ['Sauteurs']], ['SM', 'Saint Mark', ['Victoria']], ['SJ', 'Saint John', ['Gouyave']], ['CA', 'Carriacou and Petite Martinique', ['Hillsborough']]] },
  { id: 'KN', name: 'Saint Kitts and Nevis', authority: 'Inland Revenue Department', currency: 'XCD', symbol: 'EC$', regionLabel: 'Island / parish', localityLabel: 'Town / district', year: '2026', vat: 17, brackets: [[Infinity, 0]], rules: 'No personal income tax on employment income. Social security and a separate unincorporated business tax apply.', citation: 'No personal income tax statute for employment', source: ['St Kitts and Nevis Inland Revenue Department', 'https://www.sknird.com/'], locations: [['KN', 'Saint Kitts', ['Basseterre']], ['NE', 'Nevis', ['Charlestown']]] },
  { id: 'DM', name: 'Dominica', authority: 'Inland Revenue Division', currency: 'XCD', symbol: 'EC$', regionLabel: 'Parish', localityLabel: 'Town / village', year: '2026', vat: 15, allowance: 30000, brackets: [[20000, .15], [30000, .25], [Infinity, .35]], rules: 'Personal allowance then progressive bands. Social security contributions are separate.', citation: 'Income Tax Act, Chap. 67:01', source: ['Dominica Inland Revenue Division', 'https://ird.gov.dm/'], locations: [['SG', 'Saint George', ['Roseau']], ['SA', 'Saint Andrew', ['Marigot']], ['SD', 'Saint David', ['Castle Bruce']], ['SJ', 'Saint John', ['Portsmouth']], ['SL', 'Saint Luke', ['Pointe Michel']], ['SP', 'Saint Paul', ['Mahaut']], ['SPE', 'Saint Peter', ['Colihaut']]] },
  { id: 'MG', name: 'Madagascar', authority: 'Direction Generale des Impots', currency: 'MGA', symbol: 'Ar', regionLabel: 'Region', localityLabel: 'City / district', year: '2026', vat: 20, brackets: annualize([[350000, 0], [400000, .05], [500000, .1], [600000, .15], [Infinity, .2]]), rules: 'IRSA monthly salary schedule annualized. CNaPS contributions are separate.', citation: 'Code general des impots de Madagascar (IRSA)', source: ['Madagascar individual tax reference (PwC)', 'https://taxsummaries.pwc.com/madagascar/individual/taxes-on-personal-income'], locations: [['AN', 'Analamanga', ['Antananarivo']], ['AT', 'Atsinanana', ['Toamasina']], ['HM', 'Haute Matsiatra', ['Fianarantsoa']], ['BO', 'Boeny', ['Mahajanga']], ['AZ', 'Atsimo-Andrefana', ['Toliara']], ['DI', 'Diana', ['Antsiranana']], ['VK', 'Vakinankaratra', ['Antsirabe']], ['SA', 'Sava', ['Sambava']]] },
  { id: 'LI', name: 'Liechtenstein', authority: 'Steuerverwaltung', currency: 'CHF', symbol: 'CHF', regionLabel: 'Municipality', localityLabel: 'Village / area', year: '2026', vat: 8.1, allowance: 15000, brackets: [[20000, .01], [40000, .03], [70000, .04], [100000, .05], [130000, .06], [160000, .065], [200000, .07], [Infinity, .08]], rules: 'National income tax bands before the municipal multiplier, which varies by municipality and is not applied automatically.', citation: 'Steuergesetz (SteG)', source: ['Liechtenstein individual tax reference (PwC)', 'https://taxsummaries.pwc.com/liechtenstein/individual/taxes-on-personal-income'], locations: [['VA', 'Vaduz', ['Vaduz']], ['SC', 'Schaan', ['Schaan']], ['TR', 'Triesen', ['Triesen']], ['BA', 'Balzers', ['Balzers']], ['ES', 'Eschen', ['Eschen']], ['MA', 'Mauren', ['Mauren']], ['TB', 'Triesenberg', ['Triesenberg']], ['RU', 'Ruggell', ['Ruggell']]] },
  { id: 'SM', name: 'San Marino', authority: 'Ufficio Tributario', currency: 'EUR', symbol: 'EUR', regionLabel: 'Castle (municipality)', localityLabel: 'Curazia / area', year: '2026', vat: 0, allowance: 10000, brackets: [[10000, .09], [18000, .13], [28000, .17], [38000, .21], [50000, .25], [65000, .28], [80000, .31], [Infinity, .35]], rules: 'Resident employment income bands. Social security contributions and the single-phase import tax are separate.', citation: 'Legge sull imposta generale sui redditi', source: ['San Marino Ufficio Tributario', 'https://www.tributi.sm/'], locations: [['SM', 'City of San Marino', ['San Marino']], ['SE', 'Serravalle', ['Serravalle', 'Dogana']], ['BM', 'Borgo Maggiore', ['Borgo Maggiore']], ['DO', 'Domagnano', ['Domagnano']], ['FA', 'Faetano', ['Faetano']], ['FI', 'Fiorentino', ['Fiorentino']], ['AC', 'Acquaviva', ['Acquaviva']], ['CH', 'Chiesanuova', ['Chiesanuova']], ['MG', 'Montegiardino', ['Montegiardino']]] },
  { id: 'CV', name: 'Cabo Verde', authority: 'Direcao Nacional de Receitas do Estado', currency: 'CVE', symbol: 'CVE', regionLabel: 'Island', localityLabel: 'City / municipality', year: '2026', vat: 15, brackets: [[960000, .165], [1800000, .235], [Infinity, .275]], rules: 'IUR employment income bands reference. INPS contributions are separate.', citation: 'Codigo do Imposto sobre o Rendimento das Pessoas Singulares', source: ['Cabo Verde individual tax reference (PwC)', 'https://taxsummaries.pwc.com/cabo-verde/individual/taxes-on-personal-income'], locations: [['ST', 'Santiago', ['Praia']], ['SV', 'Sao Vicente', ['Mindelo']], ['SA', 'Sal', ['Espargos']], ['BV', 'Boa Vista', ['Sal Rei']], ['SN', 'Santo Antao', ['Porto Novo']], ['FO', 'Fogo', ['Sao Filipe']], ['MA', 'Maio', ['Vila do Maio']], ['SNI', 'Sao Nicolau', ['Ribeira Brava']]] },
  { id: 'PW', name: 'Palau', authority: 'Bureau of Revenue and Taxation', currency: 'USD', symbol: 'US$', regionLabel: 'State', localityLabel: 'Hamlet / area', year: '2026', vat: 10, brackets: [[8000, .06], [Infinity, .12]], rules: 'Wages and salary tax bands reference. Social security contributions are separate.', citation: 'Palau National Code, Title 40', source: ['Palau Bureau of Revenue and Taxation', 'https://www.palaugov.pw/executive-branch/ministries/finance/revenue-and-taxation/'], locations: [['KO', 'Koror', ['Koror']], ['ME', 'Melekeok', ['Ngerulmud']], ['AI', 'Airai', ['Airai']], ['NG', 'Ngatpang', ['Ngatpang']], ['PE', 'Peleliu', ['Kloulklubed']], ['AN', 'Angaur', ['Angaur']]] },
  { id: 'FM', name: 'Micronesia', authority: 'Department of Finance and Administration', currency: 'USD', symbol: 'US$', regionLabel: 'State', localityLabel: 'Municipality', year: '2026', vat: 0, brackets: [[11000, .06], [Infinity, .1]], rules: 'National wages and salary tax reference. State taxes and social security are separate.', citation: 'FSM Code, Title 54', source: ['FSM Department of Finance and Administration', 'https://dofa.gov.fm/'], locations: [['PNI', 'Pohnpei', ['Kolonia', 'Palikir']], ['CHK', 'Chuuk', ['Weno']], ['YAP', 'Yap', ['Colonia']], ['KSA', 'Kosrae', ['Tofol']]] },
  { id: 'MH', name: 'Marshall Islands', authority: 'Division of Revenue and Taxation', currency: 'USD', symbol: 'US$', regionLabel: 'Atoll / island', localityLabel: 'Town / village', year: '2026', vat: 0, brackets: [[10400, .08], [Infinity, .12]], rules: 'Wages and salaries tax reference. Social security contributions are separate.', citation: 'Marshall Islands Revised Code, Title 48', source: ['RMI Division of Revenue and Taxation', 'https://rmitax.org/'], locations: [['MAJ', 'Majuro', ['Majuro', 'Delap']], ['KWA', 'Kwajalein', ['Ebeye']], ['ARN', 'Arno', ['Arno']], ['JAL', 'Jaluit', ['Jabor']], ['WTJ', 'Wotje', ['Wotje']], ['AIL', 'Ailinglaplap', ['Airok']]] },
  { id: 'KI', name: 'Kiribati', authority: 'Ministry of Finance and Economic Development', currency: 'AUD', symbol: 'A$', regionLabel: 'Island group', localityLabel: 'Island / village', year: '2026', vat: 12.5, brackets: [[3900, 0], [10000, .2], [Infinity, .3]], rules: 'Resident income tax bands reference. Provident fund contributions are separate.', citation: 'Income Tax Act', source: ['Kiribati Ministry of Finance', 'https://www.mfed.gov.ki/'], locations: [['G', 'Gilbert Islands', ['Tarawa', 'Betio']], ['L', 'Line Islands', ['Kiritimati']], ['P', 'Phoenix Islands', ['Kanton']]] },
  { id: 'NR', name: 'Nauru', authority: 'Department of Finance', currency: 'AUD', symbol: 'A$', regionLabel: 'District', localityLabel: 'Area', year: '2026', vat: 0, brackets: [[10000, 0], [Infinity, .1]], rules: 'Employment and services tax reference. Confirm the current schedule before use.', citation: 'Employment and Services Tax Act 2014', source: ['Nauru Department of Finance', 'https://www.naurufinance.info/'], locations: [['YA', 'Yaren', ['Yaren']], ['DE', 'Denigomodu', ['Denigomodu']], ['AI', 'Aiwo', ['Aiwo']], ['ME', 'Meneng', ['Meneng']], ['BO', 'Boe', ['Boe']], ['AN', 'Anabar', ['Anabar']]] },
  { id: 'TV', name: 'Tuvalu', authority: 'Inland Revenue Department', currency: 'AUD', symbol: 'A$', regionLabel: 'Island', localityLabel: 'Village', year: '2026', vat: 7, brackets: [[2600, 0], [Infinity, .3]], rules: 'Resident income tax reference. Provident fund contributions are separate.', citation: 'Income Tax Act', source: ['Tuvalu Ministry of Finance', 'https://www.tuvalubudget.tv/'], locations: [['FUN', 'Funafuti', ['Vaiaku']], ['VAI', 'Vaitupu', ['Asau']], ['NAN', 'Nanumea', ['Nanumea']], ['NIU', 'Niutao', ['Niutao']], ['NUI', 'Nui', ['Nui']], ['NKF', 'Nukufetau', ['Savave']]] },
  { id: 'CK', name: 'Cook Islands', authority: 'Revenue Management Division', currency: 'NZD', symbol: 'NZ$', regionLabel: 'Island', localityLabel: 'Village / district', year: '2026', vat: 15, brackets: [[12800, 0], [30000, .17], [Infinity, .3]], rules: 'Resident PAYE bands reference. National superannuation contributions are separate.', citation: 'Income Tax Act 1997', source: ['Cook Islands Revenue Management Division', 'https://www.mfem.gov.ck/revenue-management'], locations: [['RAR', 'Rarotonga', ['Avarua']], ['AIT', 'Aitutaki', ['Arutanga']], ['ATI', 'Atiu', ['Areora']], ['MAU', 'Mauke', ['Areora']], ['MAN', 'Mangaia', ['Oneroa']], ['PEN', 'Penrhyn', ['Omoka']]] },
];

const curatedCountries: Record<CuratedCountryId, Country> = {
  CN: referenceCountry({
    name: 'China (mainland)', legalBody: 'State Taxation Administration', currency: 'CNY', symbol: 'CNY', locale: 'zh-CN',
    regionLabel: 'Province / municipality', localityLabel: 'City / district', taxYear: '2026', salesTax: 13,
    source: { name: 'China IIT reference (PwC Tax Summaries)', url: 'https://taxsummaries.pwc.com/peoples-republic-of-china/individual/taxes-on-personal-income' },
    rules: 'Resident annual comprehensive income uses seven progressive bands and a CNY 60,000 basic deduction. Hong Kong and Macao have separate entries and tax systems. Bonuses, non-resident withholding and treaty relief are not modeled.',
    citation: 'Individual Income Tax Law, Articles 3 and 6', allowance: 60000,
    brackets: [[36000, .03], [144000, .1], [300000, .2], [420000, .25], [660000, .3], [960000, .35], [Infinity, .45]],
    profiles: [{ value: 'resident', label: 'Resident comprehensive income', description: 'Annual resident estimate, not cumulative monthly withholding. Confirm residence and eligibility with the tax authority.' }],
    additionalAllowanceLabel: 'Eligible special additional deductions / year',
    contribution: { label: 'Social insurance & housing fund estimate', rate: 0, annualCap: 0, description: 'Enter your employee rate and annual eligible wage base. City-specific contribution floors, ceilings and housing-fund rates are not preset. Do not also enter the same cash deduction under pre-tax adjustments.', source: { name: 'State Taxation Administration', url: 'https://www.chinatax.gov.cn/eng/' } },
    locations: [
      ['BJ', 'Beijing', ['Chaoyang', 'Haidian', 'Dongcheng', 'Xicheng']], ['SH', 'Shanghai', ['Pudong', 'Huangpu', 'Xuhui']],
      ['GD', 'Guangdong', ['Guangzhou', 'Shenzhen', 'Dongguan', 'Foshan']], ['TJ', 'Tianjin', ['Heping', 'Binhai']],
      ['HE', 'Hebei', ['Shijiazhuang', 'Tangshan']], ['SX', 'Shanxi', ['Taiyuan']], ['NM', 'Inner Mongolia', ['Hohhot', 'Baotou']],
      ['LN', 'Liaoning', ['Shenyang', 'Dalian']], ['JL', 'Jilin', ['Changchun']], ['HL', 'Heilongjiang', ['Harbin']],
      ['JS', 'Jiangsu', ['Nanjing', 'Suzhou', 'Wuxi']], ['ZJ', 'Zhejiang', ['Hangzhou', 'Ningbo', 'Wenzhou']],
      ['AH', 'Anhui', ['Hefei']], ['FJ', 'Fujian', ['Fuzhou', 'Xiamen']], ['JX', 'Jiangxi', ['Nanchang']],
      ['SD', 'Shandong', ['Jinan', 'Qingdao']], ['HA', 'Henan', ['Zhengzhou']], ['HB', 'Hubei', ['Wuhan']],
      ['HN', 'Hunan', ['Changsha']], ['GX', 'Guangxi', ['Nanning', 'Guilin']], ['HI', 'Hainan', ['Haikou', 'Sanya']],
      ['CQ', 'Chongqing', ['Yuzhong', 'Jiangbei']], ['SC', 'Sichuan', ['Chengdu', 'Mianyang']], ['GZ', 'Guizhou', ['Guiyang']],
      ['YN', 'Yunnan', ['Kunming']], ['XZ', 'Tibet', ['Lhasa']], ['SN', 'Shaanxi', ['Xian']], ['GS', 'Gansu', ['Lanzhou']],
      ['QH', 'Qinghai', ['Xining']], ['NX', 'Ningxia', ['Yinchuan']], ['XJ', 'Xinjiang', ['Urumqi']],
    ],
  }),
  BN: referenceCountry({
    name: 'Brunei Darussalam', legalBody: 'Ministry of Finance and Economy', currency: 'BND', symbol: 'B$', locale: 'en-BN',
    regionLabel: 'District', localityLabel: 'Town / mukim', taxYear: '2026', salesTax: 0,
    source: { name: 'Brunei Ministry of Finance and Economy', url: 'https://www.mofe.gov.bn/' },
    rules: 'No personal income tax on employment wages. Eligible SPK members contribute separately; employer contributions and deferred TAP/SCP membership are not modeled.',
    citation: 'Brunei income tax framework; SPK member contribution guidance', brackets: [[Infinity, 0]],
    profiles: [{ value: 'resident', label: 'Employment income (no personal income tax)', description: 'Citizenship does not create a personal wage tax. Enable SPK only if you are an enrolled member.' }],
    contribution: { label: 'SPK employee contribution', rate: 8.5, annualCap: 0, description: 'SPK members contribute 8.5% of basic salary, with no contribution ceiling. Use basic salary as employment income, or enter the eligible annual base below. Employer contributions are excluded.', source: { name: 'TAP: SPK member contributions', url: 'https://tapcombn.odoo.com/spk-members-contribution' } },
    locations: [['BM', 'Brunei-Muara', ['Bandar Seri Begawan', 'Gadong', 'Berakas']], ['BE', 'Belait', ['Kuala Belait', 'Seria']], ['TU', 'Tutong', ['Pekan Tutong']], ['TE', 'Temburong', ['Bangar']]],
  }),
  BS: referenceCountry({
    name: 'Bahamas', legalBody: 'Department of Inland Revenue', currency: 'BSD', symbol: 'B$', locale: 'en-BS',
    regionLabel: 'Island / island group', localityLabel: 'Settlement', taxYear: '2026', salesTax: 10,
    source: { name: 'Bahamas Department of Inland Revenue', url: 'https://inlandrevenue.finance.gov.bs/' },
    rules: 'No personal income tax on wages. National Insurance, real property tax and VAT are separate. NIB rates and earnings ceilings can change within a calendar year; enter the applicable values explicitly.',
    citation: 'Department of Inland Revenue; National Insurance contribution guidance', brackets: [[Infinity, 0]],
    profiles: [{ value: 'resident', label: 'Personal employment income', description: 'No personal wage tax. VAT and National Insurance are not silently deducted.' }],
    contribution: { label: 'National Insurance (NIB) estimate', rate: 0, annualCap: 0, requiresCap: true, description: 'Enter the employee contribution rate for your pay date and the annual equivalent of the insurable earnings ceiling. This model does not blend mid-year rate changes.', source: { name: 'National Insurance Board', url: 'https://www.nib-bahamas.com/' } },
    locations: [['NP', 'New Providence', ['Nassau']], ['GB', 'Grand Bahama', ['Freeport', 'West End']], ['AB', 'Abaco', ['Marsh Harbour', 'Hope Town']], ['EX', 'Exuma', ['George Town']], ['EL', 'Eleuthera', ['Governors Harbour']], ['AN', 'Andros', ['Andros Town']], ['LI', 'Long Island', ['Clarence Town']], ['BI', 'Bimini', ['Alice Town']]],
  }),
  SC: referenceCountry({
    name: 'Seychelles', legalBody: 'Seychelles Revenue Commission', currency: 'SCR', symbol: 'SCR', locale: 'en-SC',
    regionLabel: 'Island / island group', localityLabel: 'District', taxYear: '2026', salesTax: 15,
    source: { name: 'SRC income and non-monetary benefits tax', url: 'https://src.gov.sc/income-and-non-monetary-benefits-tax/' },
    rules: 'SRC citizen and non-citizen employment bands differ. Monthly thresholds are annualized for this planning estimate. Employer non-monetary benefits tax and conditional exemptions are excluded.',
    citation: 'Income and Non-Monetary Benefits Tax Act; rates effective 1 June 2018',
    brackets: annualize([[8555.5, 0], [10000, .15], [83333, .2], [Infinity, .3]]),
    profiles: [
      { value: 'resident', label: 'Citizen / eligible treaty treatment', description: 'Citizen bands start with a SCR 8,555.50 monthly zero-rate band. A non-citizen must separately confirm treaty and physical-presence eligibility.' },
      { value: 'nonresident', label: 'Non-citizen standard treatment', description: '15% on the first SCR 10,000 per month, then 20% and 30%. Residence alone does not automatically establish citizen treatment.', brackets: annualize([[10000, .15], [83333, .2], [Infinity, .3]]) },
      { value: 'project', label: 'Qualifying government-agreement project', description: '3% only for an employee covered by a qualifying government or international-organization agreement.', brackets: [[Infinity, .03]] },
      { value: 'stevedore', label: 'Qualifying stevedore employment', description: '10% on qualifying dock-work emoluments under the applicable stevedore employment regulations.', brackets: [[Infinity, .1]] },
    ],
    contribution: { label: 'Seychelles Pension Fund estimate', rate: 0, annualCap: 0, description: 'Enter the applicable employee pension percentage and eligible annual base. Pension eligibility and current contribution rules must be confirmed separately.', source: { name: 'Seychelles Pension Fund', url: 'https://www.pensionfund.sc/' } },
    locations: [['MA', 'Mahe', ['English River', 'Saint Louis', 'Beau Vallon', 'Anse Royale', 'Cascade']], ['PR', 'Praslin', ['Baie Sainte Anne', 'Grand Anse Praslin']], ['LD', 'La Digue and Inner Islands', ['La Digue']], ['OI', 'Outer Islands']],
  }),
  ZM: referenceCountry({
    name: 'Zambia', legalBody: 'Zambia Revenue Authority', currency: 'ZMW', symbol: 'K', locale: 'en-ZM',
    regionLabel: 'Province', localityLabel: 'District / town', taxYear: '2026', salesTax: 16,
    source: { name: 'Zambia 2026 personal income tax (PwC)', url: 'https://taxsummaries.pwc.com/zambia/individual/taxes-on-personal-income' },
    rules: '2026 PAYE bands are 0%, 20%, 30% and 37%. The monthly zero-rate band is ZMW 5,100. Employee pension contributions are separate from PAYE; provincial selections do not add a second wage tax.',
    citation: 'Income Tax Act, Chapter 323; 2026 charge-year reference',
    brackets: [[61200, 0], [85200, .2], [110400, .3], [Infinity, .37]],
    profiles: [{ value: 'resident', label: 'Zambian-source employment (PAYE)', description: 'The same PAYE bands apply to resident and non-resident employment income within scope. Withholding on other non-resident income is not modeled.' }],
    contribution: { label: 'NAPSA employee contribution', rate: 5, annualCap: 0, requiresCap: true, description: 'Enter the annual eligible earnings ceiling for your contribution year. The 5% employee contribution is deducted from take-home, not from the PAYE tax base. Add NHIMA separately under other contributions.', source: { name: 'NAPSA contribution guidance', url: 'https://www.napsa.co.zm/' } },
    locations: [['09', 'Lusaka', ['Lusaka', 'Chongwe']], ['08', 'Copperbelt', ['Ndola', 'Kitwe', 'Chingola']], ['02', 'Central', ['Kabwe']], ['03', 'Eastern', ['Chipata']], ['04', 'Luapula', ['Mansa']], ['10', 'Muchinga', ['Chinsali']], ['05', 'Northern', ['Kasama']], ['06', 'North-Western', ['Solwezi']], ['07', 'Southern', ['Livingstone', 'Choma']], ['01', 'Western', ['Mongu']]],
  }),
  PG: referenceCountry({
    name: 'Papua New Guinea', legalBody: 'Internal Revenue Commission', currency: 'PGK', symbol: 'K', locale: 'en-PG',
    regionLabel: 'Province / autonomous region', localityLabel: 'District / town', taxYear: '2026', salesTax: 10,
    source: { name: 'PNG personal income tax reference (PwC)', url: 'https://taxsummaries.pwc.com/papua-new-guinea/individual/taxes-on-personal-income' },
    rules: 'Resident annual employment-income bands include a PGK 20,000 zero-rate threshold. Non-resident rates differ. Foreign tax credits, dependent rebates and special benefits are not automatically modeled.',
    citation: 'Salary and wages income tax reference; IRC',
    brackets: [[20000, 0], [33000, .3], [70000, .35], [250000, .4], [Infinity, .42]],
    profiles: [
      { value: 'resident', label: 'Tax resident', description: 'Resident reference with a PGK 20,000 annual zero-rate band. Enter only the income you intend to model.' },
      { value: 'nonresident', label: 'Non-resident (PNG-source employment)', description: 'Reference applies 22% to the first PGK 20,000. Confirm the effective IRC schedule for your pay date.', brackets: [[20000, .22], [33000, .3], [70000, .35], [250000, .4], [Infinity, .42]] },
    ],
    contribution: { label: 'Employee superannuation estimate', rate: 0, annualCap: 0, description: 'Enter the employee contribution rate and eligible salary base from your scheme. Employer contributions are not deducted from take-home.', source: { name: 'Internal Revenue Commission', url: 'https://irc.gov.pg/' } },
    locations: [['NCD', 'National Capital District', ['Port Moresby']], ['CPM', 'Central', ['Bereina']], ['CPK', 'Chimbu (Simbu)', ['Kundiawa']], ['EBR', 'East New Britain', ['Kokopo', 'Rabaul']], ['ESW', 'East Sepik', ['Wewak']], ['EHG', 'Eastern Highlands', ['Goroka']], ['EPW', 'Enga', ['Wabag']], ['GPK', 'Gulf', ['Kerema']], ['HLA', 'Hela', ['Tari']], ['JWK', 'Jiwaka', ['Minj']], ['MPM', 'Madang', ['Madang']], ['MRL', 'Manus', ['Lorengau']], ['MBA', 'Milne Bay', ['Alotau']], ['MPL', 'Morobe', ['Lae']], ['NIK', 'New Ireland', ['Kavieng']], ['NPP', 'Northern (Oro)', ['Popondetta']], ['NSB', 'Autonomous Region of Bougainville', ['Buka', 'Arawa']], ['SAN', 'Sandaun', ['Vanimo']], ['SHM', 'Southern Highlands', ['Mendi']], ['WPD', 'Western', ['Daru', 'Kiunga']], ['WBK', 'West New Britain', ['Kimbe']], ['WHM', 'Western Highlands', ['Mount Hagen']]],
  }),
};

const compactBuilt = Object.fromEntries(compactCountries.map(spec => [spec.id, referenceCountry({
  name: spec.name, legalBody: spec.authority, currency: spec.currency, symbol: spec.symbol, locale: spec.locale,
  regionLabel: spec.regionLabel, localityLabel: spec.localityLabel, taxYear: spec.year, salesTax: spec.vat,
  source: { name: spec.source[0], url: spec.source[1] }, rules: spec.rules, citation: spec.citation,
  allowance: spec.allowance, brackets: spec.brackets, locations: spec.locations,
  profiles: [{ value: 'resident', label: 'Resident employment income', description: `${spec.authority} dated reference. Confirm residence status, reliefs and contribution rules for your situation.` }],
  contribution: { label: `${spec.name} employee contribution estimate`, rate: 0, annualCap: 0, description: 'Enter the employee contribution rate and eligible annual wage base from your payslip or scheme. No rate is assumed automatically.', source: { name: spec.source[0], url: spec.source[1] } },
})])) as Record<CompactCountryId, Country>;

export const additionalCountries: Record<CuratedCountryId | CompactCountryId, Country> = { ...curatedCountries, ...compactBuilt };

const regionExpansions: Partial<Record<CountryId, RegionEntry[]>> = {
  DE: [['BW', 'Baden-Wurttemberg', ['Stuttgart', 'Karlsruhe', 'Freiburg']], ['BB', 'Brandenburg', ['Potsdam']], ['HB', 'Bremen', ['Bremen', 'Bremerhaven']], ['HE', 'Hesse', ['Frankfurt', 'Wiesbaden']], ['MV', 'Mecklenburg-Vorpommern', ['Schwerin', 'Rostock']], ['NI', 'Lower Saxony', ['Hanover', 'Braunschweig']], ['RP', 'Rhineland-Palatinate', ['Mainz', 'Koblenz']], ['SL', 'Saarland', ['Saarbrucken']], ['SN', 'Saxony', ['Dresden', 'Leipzig']], ['ST', 'Saxony-Anhalt', ['Magdeburg', 'Halle']], ['SH', 'Schleswig-Holstein', ['Kiel', 'Lubeck']], ['TH', 'Thuringia', ['Erfurt', 'Jena']]],
  JP: [['01', 'Hokkaido', ['Sapporo', 'Hakodate']], ['02', 'Aomori', ['Aomori']], ['03', 'Iwate', ['Morioka']], ['04', 'Miyagi', ['Sendai']], ['05', 'Akita', ['Akita']], ['06', 'Yamagata', ['Yamagata']], ['07', 'Fukushima', ['Fukushima', 'Koriyama']], ['08', 'Ibaraki', ['Mito', 'Tsukuba']], ['09', 'Tochigi', ['Utsunomiya']], ['10', 'Gunma', ['Maebashi']], ['11', 'Saitama', ['Saitama', 'Kawaguchi']], ['12', 'Chiba', ['Chiba', 'Funabashi']], ['14', 'Kanagawa', ['Yokohama', 'Kawasaki']], ['15', 'Niigata', ['Niigata']], ['16', 'Toyama', ['Toyama']], ['17', 'Ishikawa', ['Kanazawa']], ['18', 'Fukui', ['Fukui']], ['19', 'Yamanashi', ['Kofu']], ['20', 'Nagano', ['Nagano', 'Matsumoto']], ['21', 'Gifu', ['Gifu']], ['22', 'Shizuoka', ['Shizuoka', 'Hamamatsu']], ['23', 'Aichi', ['Nagoya']], ['24', 'Mie', ['Tsu']], ['25', 'Shiga', ['Otsu']], ['28', 'Hyogo', ['Kobe', 'Himeji']], ['29', 'Nara', ['Nara']], ['30', 'Wakayama', ['Wakayama']], ['31', 'Tottori', ['Tottori']], ['32', 'Shimane', ['Matsue']], ['33', 'Okayama', ['Okayama']], ['34', 'Hiroshima', ['Hiroshima']], ['35', 'Yamaguchi', ['Yamaguchi']], ['36', 'Tokushima', ['Tokushima']], ['37', 'Kagawa', ['Takamatsu']], ['38', 'Ehime', ['Matsuyama']], ['39', 'Kochi', ['Kochi']], ['40', 'Fukuoka', ['Fukuoka', 'Kitakyushu']], ['41', 'Saga', ['Saga']], ['42', 'Nagasaki', ['Nagasaki']], ['43', 'Kumamoto', ['Kumamoto']], ['44', 'Oita', ['Oita']], ['45', 'Miyazaki', ['Miyazaki']], ['46', 'Kagoshima', ['Kagoshima']], ['47', 'Okinawa', ['Naha']]],
  IN: [['AP', 'Andhra Pradesh', ['Visakhapatnam', 'Vijayawada']], ['AR', 'Arunachal Pradesh', ['Itanagar']], ['AS', 'Assam', ['Guwahati']], ['BR', 'Bihar', ['Patna']], ['CG', 'Chhattisgarh', ['Raipur']], ['GA', 'Goa', ['Panaji']], ['GJ', 'Gujarat', ['Ahmedabad', 'Surat']], ['HR', 'Haryana', ['Gurugram', 'Faridabad']], ['HP', 'Himachal Pradesh', ['Shimla']], ['JH', 'Jharkhand', ['Ranchi']], ['KL', 'Kerala', ['Kochi', 'Thiruvananthapuram']], ['MP', 'Madhya Pradesh', ['Bhopal', 'Indore']], ['MN', 'Manipur', ['Imphal']], ['ML', 'Meghalaya', ['Shillong']], ['MZ', 'Mizoram', ['Aizawl']], ['NL', 'Nagaland', ['Kohima']], ['OD', 'Odisha', ['Bhubaneswar']], ['PB', 'Punjab', ['Ludhiana', 'Amritsar']], ['RJ', 'Rajasthan', ['Jaipur']], ['SK', 'Sikkim', ['Gangtok']], ['TN', 'Tamil Nadu', ['Chennai', 'Coimbatore']], ['TS', 'Telangana', ['Hyderabad']], ['TR', 'Tripura', ['Agartala']], ['UP', 'Uttar Pradesh', ['Lucknow', 'Noida']], ['UK', 'Uttarakhand', ['Dehradun']], ['WB', 'West Bengal', ['Kolkata']], ['AN', 'Andaman and Nicobar Islands', ['Sri Vijaya Puram']], ['CH', 'Chandigarh', ['Chandigarh']], ['DH', 'Dadra and Nagar Haveli and Daman and Diu', ['Daman', 'Silvassa']], ['JK', 'Jammu and Kashmir', ['Srinagar', 'Jammu']], ['LA', 'Ladakh', ['Leh']], ['LD', 'Lakshadweep', ['Kavaratti']], ['PY', 'Puducherry', ['Puducherry']]],
  NZ: [['NTL', 'Northland', ['Whangarei']], ['WKO', 'Waikato', ['Hamilton']], ['BOP', 'Bay of Plenty', ['Tauranga', 'Rotorua']], ['GIS', 'Gisborne', ['Gisborne']], ['HKB', 'Hawkes Bay', ['Napier', 'Hastings']], ['TKI', 'Taranaki', ['New Plymouth']], ['MWT', 'Manawatu-Whanganui', ['Palmerston North', 'Whanganui']], ['TAS', 'Tasman', ['Richmond']], ['NSN', 'Nelson', ['Nelson']], ['MBH', 'Marlborough', ['Blenheim']], ['WTC', 'West Coast', ['Greymouth']], ['CAN', 'Canterbury', ['Christchurch']], ['OTA', 'Otago', ['Dunedin', 'Queenstown']], ['STL', 'Southland', ['Invercargill']]],
  ES: [['ES-AN', 'Andalusia', ['Seville', 'Malaga']], ['ES-AR', 'Aragon', ['Zaragoza']], ['ES-AS', 'Asturias', ['Oviedo', 'Gijon']], ['ES-IB', 'Balearic Islands', ['Palma']], ['ES-PV', 'Basque Country', ['Bilbao', 'San Sebastian']], ['ES-CN', 'Canary Islands', ['Las Palmas', 'Santa Cruz de Tenerife']], ['ES-CB', 'Cantabria', ['Santander']], ['ES-CM', 'Castilla-La Mancha', ['Toledo', 'Albacete']], ['ES-CL', 'Castile and Leon', ['Valladolid', 'Salamanca']], ['ES-EX', 'Extremadura', ['Merida', 'Badajoz']], ['ES-GA', 'Galicia', ['A Coruna', 'Vigo']], ['ES-RI', 'La Rioja', ['Logrono']], ['ES-MC', 'Murcia', ['Murcia', 'Cartagena']], ['ES-NC', 'Navarre', ['Pamplona']], ['ES-VC', 'Valencian Community', ['Valencia', 'Alicante']]],
  IT: [['IT-ABR', 'Abruzzo', ['Pescara']], ['IT-BAS', 'Basilicata', ['Potenza']], ['IT-CAL', 'Calabria', ['Catanzaro', 'Reggio Calabria']], ['IT-CAM', 'Campania', ['Naples', 'Salerno']], ['IT-EMR', 'Emilia-Romagna', ['Bologna', 'Modena']], ['IT-FVG', 'Friuli-Venezia Giulia', ['Trieste', 'Udine']], ['IT-LIG', 'Liguria', ['Genoa']], ['IT-MAR', 'Marche', ['Ancona']], ['IT-MOL', 'Molise', ['Campobasso']], ['IT-PMN', 'Piedmont', ['Turin']], ['IT-PUG', 'Apulia', ['Bari', 'Taranto']], ['IT-SAR', 'Sardinia', ['Cagliari']], ['IT-SIC', 'Sicily', ['Palermo', 'Catania']], ['IT-TAA', 'Trentino-Alto Adige', ['Trento', 'Bolzano']], ['IT-TOS', 'Tuscany', ['Florence', 'Pisa']], ['IT-UMB', 'Umbria', ['Perugia']], ['IT-VDA', 'Aosta Valley', ['Aosta']], ['IT-VEN', 'Veneto', ['Venice', 'Verona']]],
  MX: [['MX-JAL', 'Jalisco', ['Guadalajara']], ['MX-MEX', 'State of Mexico', ['Toluca', 'Ecatepec']], ['MX-PUE', 'Puebla', ['Puebla']], ['MX-GTO', 'Guanajuato', ['Leon']], ['MX-CHH', 'Chihuahua', ['Ciudad Juarez']], ['MX-BCN', 'Baja California', ['Tijuana', 'Mexicali']], ['MX-VER', 'Veracruz', ['Veracruz', 'Xalapa']], ['MX-YUC', 'Yucatan', ['Merida']], ['MX-QUE', 'Queretaro', ['Queretaro']], ['MX-COA', 'Coahuila', ['Saltillo', 'Torreon']], ['MX-SON', 'Sonora', ['Hermosillo']], ['MX-SIN', 'Sinaloa', ['Culiacan']], ['MX-MIC', 'Michoacan', ['Morelia']], ['MX-OAX', 'Oaxaca', ['Oaxaca']], ['MX-CHP', 'Chiapas', ['Tuxtla Gutierrez']], ['MX-ROO', 'Quintana Roo', ['Cancun']]],
  BR: [['BR-RJ', 'Rio de Janeiro', ['Rio de Janeiro', 'Niteroi']], ['BR-MG', 'Minas Gerais', ['Belo Horizonte']], ['BR-BA', 'Bahia', ['Salvador']], ['BR-PR', 'Parana', ['Curitiba']], ['BR-RS', 'Rio Grande do Sul', ['Porto Alegre']], ['BR-PE', 'Pernambuco', ['Recife']], ['BR-CE', 'Ceara', ['Fortaleza']], ['BR-SC', 'Santa Catarina', ['Florianopolis', 'Joinville']], ['BR-GO', 'Goias', ['Goiania']], ['BR-DF', 'Federal District', ['Brasilia']], ['BR-ES', 'Espirito Santo', ['Vitoria']], ['BR-PA', 'Para', ['Belem']], ['BR-AM', 'Amazonas', ['Manaus']], ['BR-MT', 'Mato Grosso', ['Cuiaba']], ['BR-MS', 'Mato Grosso do Sul', ['Campo Grande']]],
  FR: [['FR-BFC', 'Bourgogne-Franche-Comte', ['Dijon']], ['FR-BRE', 'Brittany', ['Rennes', 'Brest']], ['FR-CVL', 'Centre-Val de Loire', ['Orleans', 'Tours']], ['FR-GES', 'Grand Est', ['Strasbourg', 'Reims']], ['FR-HDF', 'Hauts-de-France', ['Lille']], ['FR-NOR', 'Normandy', ['Rouen', 'Caen']], ['FR-NAQ', 'Nouvelle-Aquitaine', ['Bordeaux']], ['FR-OCC', 'Occitanie', ['Toulouse', 'Montpellier']], ['FR-PDL', 'Pays de la Loire', ['Nantes']], ['FR-COR', 'Corsica', ['Ajaccio']]],
  PL: [['PL-DS', 'Lower Silesia', ['Wroclaw']], ['PL-KP', 'Kuyavia-Pomerania', ['Bydgoszcz']], ['PL-LU', 'Lublin', ['Lublin']], ['PL-LB', 'Lubusz', ['Zielona Gora']], ['PL-LD', 'Lodz', ['Lodz']], ['PL-MA', 'Lesser Poland', ['Krakow']], ['PL-OP', 'Opole', ['Opole']], ['PL-PK', 'Subcarpathia', ['Rzeszow']], ['PL-PD', 'Podlaskie', ['Bialystok']], ['PL-PM', 'Pomerania', ['Gdansk']], ['PL-SL', 'Silesia', ['Katowice']], ['PL-SK', 'Holy Cross', ['Kielce']], ['PL-WN', 'Warmia-Masuria', ['Olsztyn']], ['PL-WP', 'Greater Poland', ['Poznan']], ['PL-ZP', 'West Pomerania', ['Szczecin']]],
  NL: [['NL-UT', 'Utrecht', ['Utrecht']], ['NL-NB', 'North Brabant', ['Eindhoven', 'Tilburg']], ['NL-GE', 'Gelderland', ['Arnhem', 'Nijmegen']], ['NL-OV', 'Overijssel', ['Zwolle', 'Enschede']], ['NL-LI', 'Limburg', ['Maastricht']], ['NL-FR', 'Friesland', ['Leeuwarden']], ['NL-GR', 'Groningen', ['Groningen']], ['NL-DR', 'Drenthe', ['Assen']], ['NL-FL', 'Flevoland', ['Almere']], ['NL-ZE', 'Zeeland', ['Middelburg']]],
  ZA: [['ZA-KZN', 'KwaZulu-Natal', ['Durban']], ['ZA-EC', 'Eastern Cape', ['Gqeberha', 'East London']], ['ZA-FS', 'Free State', ['Bloemfontein']], ['ZA-LP', 'Limpopo', ['Polokwane']], ['ZA-MP', 'Mpumalanga', ['Mbombela']], ['ZA-NC', 'Northern Cape', ['Kimberley']], ['ZA-NW', 'North West', ['Mahikeng']]],
  AR: [['AR-CBA', 'Cordoba', ['Cordoba']], ['AR-SFE', 'Santa Fe', ['Rosario', 'Santa Fe']], ['AR-MZA', 'Mendoza', ['Mendoza']], ['AR-TUC', 'Tucuman', ['San Miguel de Tucuman']], ['AR-SAL', 'Salta', ['Salta']], ['AR-ERI', 'Entre Rios', ['Parana']], ['AR-NQN', 'Neuquen', ['Neuquen']], ['AR-CHU', 'Chubut', ['Comodoro Rivadavia']], ['AR-RNG', 'Rio Negro', ['Viedma']], ['AR-MIS', 'Misiones', ['Posadas']]],
  PH: [['PH-CAR', 'Cordillera Administrative Region', ['Baguio']], ['PH-R03', 'Central Luzon', ['Angeles', 'San Fernando']], ['PH-R4A', 'Calabarzon', ['Calamba', 'Antipolo']], ['PH-R06', 'Western Visayas', ['Iloilo City']], ['PH-R07', 'Central Visayas', ['Cebu City']], ['PH-R08', 'Eastern Visayas', ['Tacloban']], ['PH-R10', 'Northern Mindanao', ['Cagayan de Oro']], ['PH-R11', 'Davao Region', ['Davao City']], ['PH-R01', 'Ilocos Region', ['San Fernando, La Union']], ['PH-BAR', 'Bangsamoro', ['Cotabato City']]],
  ID: [['ID-JB', 'West Java', ['Bandung', 'Bekasi']], ['ID-JT', 'Central Java', ['Semarang', 'Surakarta']], ['ID-JI', 'East Java', ['Surabaya', 'Malang']], ['ID-BT', 'Banten', ['Tangerang']], ['ID-BA', 'Bali', ['Denpasar']], ['ID-SU', 'North Sumatra', ['Medan']], ['ID-SS', 'South Sumatra', ['Palembang']], ['ID-RI', 'Riau', ['Pekanbaru']], ['ID-KI', 'East Kalimantan', ['Samarinda', 'Balikpapan']], ['ID-SN', 'South Sulawesi', ['Makassar']], ['ID-YO', 'Yogyakarta', ['Yogyakarta']], ['ID-PA', 'Papua', ['Jayapura']]],
  MY: [['MY-14', 'Kuala Lumpur', ['Kuala Lumpur']], ['MY-10', 'Selangor', ['Shah Alam', 'Petaling Jaya']], ['MY-07', 'Penang', ['George Town']], ['MY-01', 'Johor', ['Johor Bahru']], ['MY-06', 'Pahang', ['Kuantan']], ['MY-08', 'Perak', ['Ipoh']], ['MY-12', 'Sabah', ['Kota Kinabalu']], ['MY-13', 'Sarawak', ['Kuching']], ['MY-04', 'Melaka', ['Melaka City']], ['MY-05', 'Negeri Sembilan', ['Seremban']], ['MY-02', 'Kedah', ['Alor Setar']], ['MY-03', 'Kelantan', ['Kota Bharu']], ['MY-11', 'Terengganu', ['Kuala Terengganu']], ['MY-09', 'Perlis', ['Kangar']]],
  KR: [['KR-26', 'Busan', ['Busan']], ['KR-27', 'Daegu', ['Daegu']], ['KR-28', 'Incheon', ['Incheon']], ['KR-29', 'Gwangju', ['Gwangju']], ['KR-30', 'Daejeon', ['Daejeon']], ['KR-31', 'Ulsan', ['Ulsan']], ['KR-41', 'Gyeonggi', ['Suwon', 'Seongnam']], ['KR-42', 'Gangwon', ['Chuncheon']], ['KR-43', 'North Chungcheong', ['Cheongju']], ['KR-44', 'South Chungcheong', ['Cheonan']], ['KR-45', 'North Jeolla', ['Jeonju']], ['KR-46', 'South Jeolla', ['Yeosu']], ['KR-47', 'North Gyeongsang', ['Pohang']], ['KR-48', 'South Gyeongsang', ['Changwon']], ['KR-49', 'Jeju', ['Jeju City']]],
  SE: [['SE-VG', 'Vastra Gotaland', ['Gothenburg']], ['SE-SK', 'Skane', ['Malmo', 'Lund']], ['SE-UP', 'Uppsala', ['Uppsala']], ['SE-OG', 'Ostergotland', ['Linkoping']], ['SE-JO', 'Jonkoping', ['Jonkoping']], ['SE-VB', 'Vasterbotten', ['Umea']], ['SE-NB', 'Norrbotten', ['Lulea']], ['SE-VM', 'Vastmanland', ['Vasteras']], ['SE-OR', 'Orebro', ['Orebro']], ['SE-GV', 'Gavleborg', ['Gavle']]],
  NO: [['NO-11', 'Rogaland', ['Stavanger']], ['NO-46', 'Vestland', ['Bergen']], ['NO-50', 'Trondelag', ['Trondheim']], ['NO-18', 'Nordland', ['Bodo']], ['NO-31', 'Ostfold', ['Fredrikstad']], ['NO-32', 'Akershus', ['Baerum']], ['NO-33', 'Buskerud', ['Drammen']], ['NO-34', 'Innlandet', ['Hamar']], ['NO-39', 'Vestfold', ['Tonsberg']], ['NO-40', 'Telemark', ['Skien']], ['NO-55', 'Troms', ['Tromso']], ['NO-56', 'Finnmark', ['Alta']]],
  DK: [['DK-82', 'Central Denmark', ['Aarhus']], ['DK-81', 'North Denmark', ['Aalborg']], ['DK-83', 'Southern Denmark', ['Odense', 'Esbjerg']], ['DK-85', 'Zealand', ['Roskilde']]],
  FI: [['FI-19', 'Southwest Finland', ['Turku']], ['FI-11', 'Pirkanmaa', ['Tampere']], ['FI-14', 'North Ostrobothnia', ['Oulu']], ['FI-09', 'North Savo', ['Kuopio']], ['FI-07', 'Central Finland', ['Jyvaskyla']], ['FI-05', 'Kymenlaakso', ['Kotka']], ['FI-17', 'Satakunta', ['Pori']], ['FI-10', 'Lapland', ['Rovaniemi']]],
  PT: [['PT-POR', 'Porto', ['Porto']], ['PT-BRG', 'Braga', ['Braga']], ['PT-CBR', 'Coimbra', ['Coimbra']], ['PT-FAR', 'Algarve (Faro)', ['Faro']], ['PT-SET', 'Setubal', ['Setubal']], ['PT-AVE', 'Aveiro', ['Aveiro']], ['PT-30', 'Madeira', ['Funchal']], ['PT-20', 'Azores', ['Ponta Delgada']]],
  GR: [['GR-B', 'Central Macedonia', ['Thessaloniki']], ['GR-C', 'Western Macedonia', ['Kozani']], ['GR-D', 'Epirus', ['Ioannina']], ['GR-E', 'Thessaly', ['Larissa', 'Volos']], ['GR-F', 'Ionian Islands', ['Corfu']], ['GR-G', 'Western Greece', ['Patras']], ['GR-H', 'Central Greece', ['Lamia']], ['GR-J', 'Peloponnese', ['Kalamata']], ['GR-K', 'North Aegean', ['Mytilene']], ['GR-L', 'South Aegean', ['Rhodes']], ['GR-M', 'Crete', ['Heraklion']]],
  TR: [['TR-06', 'Ankara', ['Ankara']], ['TR-35', 'Izmir', ['Izmir']], ['TR-16', 'Bursa', ['Bursa']], ['TR-07', 'Antalya', ['Antalya']], ['TR-01', 'Adana', ['Adana']], ['TR-42', 'Konya', ['Konya']], ['TR-33', 'Mersin', ['Mersin']], ['TR-27', 'Gaziantep', ['Gaziantep']], ['TR-41', 'Kocaeli', ['Izmit']], ['TR-61', 'Trabzon', ['Trabzon']], ['TR-21', 'Diyarbakir', ['Diyarbakir']], ['TR-38', 'Kayseri', ['Kayseri']]],
  CO: [['CO-ANT', 'Antioquia', ['Medellin']], ['CO-VAC', 'Valle del Cauca', ['Cali']], ['CO-ATL', 'Atlantico', ['Barranquilla']], ['CO-SAN', 'Santander', ['Bucaramanga']], ['CO-BOL', 'Bolivar', ['Cartagena']], ['CO-CUN', 'Cundinamarca', ['Soacha']], ['CO-RIS', 'Risaralda', ['Pereira']], ['CO-CAL', 'Caldas', ['Manizales']], ['CO-NSA', 'Norte de Santander', ['Cucuta']], ['CO-TOL', 'Tolima', ['Ibague']]],
  CL: [['CL-VS', 'Valparaiso', ['Valparaiso', 'Vina del Mar']], ['CL-BI', 'Biobio', ['Concepcion']], ['CL-AR', 'Araucania', ['Temuco']], ['CL-LL', 'Los Lagos', ['Puerto Montt']], ['CL-AN', 'Antofagasta', ['Antofagasta']], ['CL-CO', 'Coquimbo', ['La Serena']], ['CL-ML', 'Maule', ['Talca']], ['CL-LI', 'Libertador General Bernardo OHiggins', ['Rancagua']], ['CL-TA', 'Tarapaca', ['Iquique']], ['CL-MA', 'Magallanes', ['Punta Arenas']]],
  NG: [['NG-RI', 'Rivers', ['Port Harcourt']], ['NG-KN', 'Kano', ['Kano']], ['NG-OY', 'Oyo', ['Ibadan']], ['NG-KD', 'Kaduna', ['Kaduna']], ['NG-AB', 'Abia', ['Aba', 'Umuahia']], ['NG-AN', 'Anambra', ['Onitsha', 'Awka']], ['NG-DE', 'Delta', ['Warri', 'Asaba']], ['NG-ED', 'Edo', ['Benin City']], ['NG-EN', 'Enugu', ['Enugu']], ['NG-OG', 'Ogun', ['Abeokuta']], ['NG-PL', 'Plateau', ['Jos']], ['NG-BO', 'Borno', ['Maiduguri']]],
  KE: [['KE-36', 'Mombasa', ['Mombasa']], ['KE-25', 'Kisumu', ['Kisumu']], ['KE-32', 'Nakuru', ['Nakuru']], ['KE-45', 'Uasin Gishu', ['Eldoret']], ['KE-22', 'Kiambu', ['Thika']], ['KE-26', 'Kisii', ['Kisii']], ['KE-23', 'Kilifi', ['Malindi']], ['KE-28', 'Machakos', ['Machakos']], ['KE-31', 'Meru', ['Meru']], ['KE-16', 'Kakamega', ['Kakamega']]],
  EG: [['EG-ALX', 'Alexandria', ['Alexandria']], ['EG-GZ', 'Giza', ['Giza', '6th of October']], ['EG-SHR', 'Sharqia', ['Zagazig']], ['EG-DK', 'Dakahlia', ['Mansoura']], ['EG-BH', 'Beheira', ['Damanhur']], ['EG-PTS', 'Port Said', ['Port Said']], ['EG-SUZ', 'Suez', ['Suez']], ['EG-ASN', 'Aswan', ['Aswan']], ['EG-LX', 'Luxor', ['Luxor']], ['EG-BNS', 'Beni Suef', ['Beni Suef']]],
  PK: [['PK-SD', 'Sindh', ['Karachi', 'Hyderabad']], ['PK-KP', 'Khyber Pakhtunkhwa', ['Peshawar']], ['PK-BA', 'Balochistan', ['Quetta']], ['PK-IS', 'Islamabad Capital Territory', ['Islamabad']], ['PK-GB', 'Gilgit-Baltistan', ['Gilgit']], ['PK-JK', 'Azad Jammu and Kashmir', ['Muzaffarabad']]],
  BD: [['BD-C', 'Chattogram', ['Chattogram']], ['BD-D', 'Dhaka Division', ['Gazipur', 'Narayanganj']], ['BD-E', 'Khulna', ['Khulna']], ['BD-F', 'Rajshahi', ['Rajshahi']], ['BD-G', 'Sylhet', ['Sylhet']], ['BD-H', 'Barishal', ['Barishal']], ['BD-I', 'Rangpur', ['Rangpur']], ['BD-J', 'Mymensingh', ['Mymensingh']]],
  VN: [['VN-SG', 'Ho Chi Minh City', ['Ho Chi Minh City']], ['VN-DN', 'Da Nang', ['Da Nang']], ['VN-HP', 'Hai Phong', ['Hai Phong']], ['VN-CT', 'Can Tho', ['Can Tho']], ['VN-BN', 'Bac Ninh', ['Bac Ninh']], ['VN-BD', 'Binh Duong', ['Thu Dau Mot']], ['VN-DNA', 'Dong Nai', ['Bien Hoa']], ['VN-QN', 'Quang Ninh', ['Ha Long']], ['VN-KH', 'Khanh Hoa', ['Nha Trang']], ['VN-TTH', 'Hue', ['Hue']]],
  TH: [['TH-50', 'Chiang Mai', ['Chiang Mai']], ['TH-83', 'Phuket', ['Phuket']], ['TH-20', 'Chonburi', ['Pattaya', 'Chonburi']], ['TH-90', 'Songkhla', ['Hat Yai']], ['TH-40', 'Khon Kaen', ['Khon Kaen']], ['TH-30', 'Nakhon Ratchasima', ['Nakhon Ratchasima']], ['TH-11', 'Samut Prakan', ['Samut Prakan']], ['TH-12', 'Nonthaburi', ['Nonthaburi']], ['TH-73', 'Nakhon Pathom', ['Nakhon Pathom']], ['TH-84', 'Surat Thani', ['Surat Thani']]],
  SA: [['SA-02', 'Makkah', ['Jeddah', 'Mecca']], ['SA-04', 'Eastern Province', ['Dammam', 'Khobar']], ['SA-03', 'Madinah', ['Medina']], ['SA-05', 'Qassim', ['Buraydah']], ['SA-06', 'Hail', ['Hail']], ['SA-08', 'Northern Borders', ['Arar']], ['SA-09', 'Jazan', ['Jazan']], ['SA-10', 'Najran', ['Najran']], ['SA-11', 'Al Bahah', ['Al Bahah']], ['SA-14', 'Asir', ['Abha']], ['SA-07', 'Tabuk', ['Tabuk']]],
  AE: [['AE-SHJ', 'Sharjah', ['Sharjah']], ['AE-AJM', 'Ajman', ['Ajman']], ['AE-RAK', 'Ras Al Khaimah', ['Ras Al Khaimah']], ['AE-FUJ', 'Fujairah', ['Fujairah']], ['AE-UAQ', 'Umm Al Quwain', ['Umm Al Quwain']]],
  CZ: [['CZ-JM', 'South Moravian', ['Brno']], ['CZ-MO', 'Moravian-Silesian', ['Ostrava']], ['CZ-OL', 'Olomouc', ['Olomouc']], ['CZ-PL', 'Plzen', ['Plzen']], ['CZ-JC', 'South Bohemian', ['Ceske Budejovice']], ['CZ-KR', 'Hradec Kralove', ['Hradec Kralove']], ['CZ-LI', 'Liberec', ['Liberec']], ['CZ-US', 'Usti nad Labem', ['Usti nad Labem']], ['CZ-ZL', 'Zlin', ['Zlin']], ['CZ-PA', 'Pardubice', ['Pardubice']]],
  RO: [['RO-CJ', 'Cluj', ['Cluj-Napoca']], ['RO-TM', 'Timis', ['Timisoara']], ['RO-IS', 'Iasi', ['Iasi']], ['RO-CT', 'Constanta', ['Constanta']], ['RO-BV', 'Brasov', ['Brasov']], ['RO-DJ', 'Dolj', ['Craiova']], ['RO-GL', 'Galati', ['Galati']], ['RO-SB', 'Sibiu', ['Sibiu']], ['RO-AG', 'Arges', ['Pitesti']], ['RO-BC', 'Bacau', ['Bacau']]],
  HU: [['HU-PE', 'Pest', ['Erd', 'Godollo']], ['HU-HB', 'Hajdu-Bihar', ['Debrecen']], ['HU-CS', 'Csongrad-Csanad', ['Szeged']], ['HU-BA', 'Baranya', ['Pecs']], ['HU-GS', 'Gyor-Moson-Sopron', ['Gyor']], ['HU-BZ', 'Borsod-Abauj-Zemplen', ['Miskolc']], ['HU-SZ', 'Szabolcs-Szatmar-Bereg', ['Nyiregyhaza']], ['HU-FE', 'Fejer', ['Szekesfehervar']]],
  IE: [['IE-CK', 'Cork', ['Cork']], ['IE-G', 'Galway', ['Galway']], ['IE-LK', 'Limerick', ['Limerick']], ['IE-WD', 'Waterford', ['Waterford']], ['IE-KE', 'Kildare', ['Naas']], ['IE-MH', 'Meath', ['Navan']], ['IE-WH', 'Westmeath', ['Athlone']], ['IE-DL', 'Donegal', ['Letterkenny']], ['IE-KY', 'Kerry', ['Tralee']], ['IE-MO', 'Mayo', ['Castlebar']]],
  AT: [['AT-1', 'Burgenland', ['Eisenstadt']], ['AT-2', 'Carinthia', ['Klagenfurt']], ['AT-3', 'Lower Austria', ['St. Polten']], ['AT-4', 'Upper Austria', ['Linz']], ['AT-5', 'Salzburg', ['Salzburg']], ['AT-6', 'Styria', ['Graz']], ['AT-7', 'Tyrol', ['Innsbruck']], ['AT-8', 'Vorarlberg', ['Bregenz']]],
  BE: [['BE-VAN', 'Antwerp', ['Antwerp']], ['BE-VOV', 'East Flanders', ['Ghent']], ['BE-VLI', 'Limburg', ['Hasselt']], ['BE-VBR', 'Flemish Brabant', ['Leuven']], ['BE-VWV', 'West Flanders', ['Bruges']], ['BE-WLG', 'Liege', ['Liege']], ['BE-WHT', 'Hainaut', ['Charleroi', 'Mons']], ['BE-WNA', 'Namur', ['Namur']], ['BE-WBR', 'Walloon Brabant', ['Wavre']], ['BE-WLX', 'Luxembourg province', ['Arlon']]],
  CH: [['CH-BE', 'Bern', ['Bern']], ['CH-VD', 'Vaud', ['Lausanne']], ['CH-BS', 'Basel-Stadt', ['Basel']], ['CH-BL', 'Basel-Landschaft', ['Liestal']], ['CH-LU', 'Lucerne', ['Lucerne']], ['CH-SG', 'St. Gallen', ['St. Gallen']], ['CH-TI', 'Ticino', ['Lugano']], ['CH-AG', 'Aargau', ['Aarau']], ['CH-ZG', 'Zug', ['Zug']], ['CH-VS', 'Valais', ['Sion']], ['CH-FR', 'Fribourg', ['Fribourg']], ['CH-NE', 'Neuchatel', ['Neuchatel']]],
  SG: [['SG-CR', 'Central Region', ['Downtown Core', 'Queenstown']], ['SG-ER', 'East Region', ['Bedok', 'Tampines']], ['SG-NR', 'North Region', ['Woodlands', 'Yishun']], ['SG-NE', 'North-East Region', ['Hougang', 'Punggol']], ['SG-WR', 'West Region', ['Jurong West', 'Clementi']]],
  HK: [['HK-KL', 'Kowloon', ['Yau Tsim Mong', 'Kwun Tong']], ['HK-NT', 'New Territories', ['Sha Tin', 'Tsuen Wan']]],
  TW: [['TW-NWT', 'New Taipei', ['Banqiao']], ['TW-TAO', 'Taoyuan', ['Taoyuan']], ['TW-TXG', 'Taichung', ['Taichung']], ['TW-TNN', 'Tainan', ['Tainan']], ['TW-KHH', 'Kaohsiung', ['Kaohsiung']], ['TW-HSZ', 'Hsinchu', ['Hsinchu']], ['TW-CYI', 'Chiayi', ['Chiayi']], ['TW-KEE', 'Keelung', ['Keelung']]],
  MA: [['MA-CAS', 'Casablanca-Settat', ['Casablanca']], ['MA-MAR', 'Marrakesh-Safi', ['Marrakesh']], ['MA-FES', 'Fes-Meknes', ['Fes', 'Meknes']], ['MA-TAN', 'Tangier-Tetouan-Al Hoceima', ['Tangier']], ['MA-ORI', 'Oriental', ['Oujda']], ['MA-SOU', 'Souss-Massa', ['Agadir']], ['MA-BEN', 'Beni Mellal-Khenifra', ['Beni Mellal']], ['MA-DRA', 'Draa-Tafilalet', ['Errachidia']]],
  PE: [['PE-ARE', 'Arequipa', ['Arequipa']], ['PE-LAL', 'La Libertad', ['Trujillo']], ['PE-LAM', 'Lambayeque', ['Chiclayo']], ['PE-PIU', 'Piura', ['Piura']], ['PE-CUS', 'Cusco', ['Cusco']], ['PE-JUN', 'Junin', ['Huancayo']], ['PE-ANC', 'Ancash', ['Chimbote']], ['PE-ICA', 'Ica', ['Ica']], ['PE-LOR', 'Loreto', ['Iquitos']], ['PE-PUN', 'Puno', ['Juliaca']]],
  EC: [['EC-G', 'Guayas', ['Guayaquil']], ['EC-A', 'Azuay', ['Cuenca']], ['EC-M', 'Manabi', ['Portoviejo', 'Manta']], ['EC-E', 'Esmeraldas', ['Esmeraldas']], ['EC-O', 'El Oro', ['Machala']], ['EC-T', 'Tungurahua', ['Ambato']], ['EC-I', 'Imbabura', ['Ibarra']], ['EC-L', 'Loja', ['Loja']]],
  LK: [['LK-2', 'Central Province', ['Kandy']], ['LK-3', 'Southern Province', ['Galle']], ['LK-4', 'Northern Province', ['Jaffna']], ['LK-5', 'Eastern Province', ['Trincomalee']], ['LK-6', 'North Western Province', ['Kurunegala']], ['LK-7', 'North Central Province', ['Anuradhapura']], ['LK-8', 'Uva Province', ['Badulla']], ['LK-9', 'Sabaragamuwa Province', ['Ratnapura']]],
  GH: [['GH-AH', 'Ashanti', ['Kumasi']], ['GH-WP', 'Western', ['Sekondi-Takoradi']], ['GH-EP', 'Eastern', ['Koforidua']], ['GH-CP', 'Central', ['Cape Coast']], ['GH-NP', 'Northern', ['Tamale']], ['GH-VO', 'Volta', ['Ho']], ['GH-BO', 'Bono', ['Sunyani']], ['GH-UE', 'Upper East', ['Bolgatanga']]],
  TZ: [['TZ-02', 'Arusha', ['Arusha']], ['TZ-12', 'Mwanza', ['Mwanza']], ['TZ-05', 'Dodoma', ['Dodoma']], ['TZ-09', 'Kilimanjaro', ['Moshi']], ['TZ-14', 'Mbeya', ['Mbeya']], ['TZ-21', 'Tanga', ['Tanga']], ['TZ-31', 'Zanzibar Urban/West', ['Zanzibar City']], ['TZ-13', 'Morogoro', ['Morogoro']]],
  UG: [['UG-C', 'Central Region', ['Entebbe', 'Wakiso']], ['UG-E', 'Eastern Region', ['Jinja', 'Mbale']], ['UG-N', 'Northern Region', ['Gulu', 'Lira']], ['UG-W', 'Western Region', ['Mbarara', 'Fort Portal']]],
  KZ: [['KZ-ALA', 'Almaty City', ['Almaty']], ['KZ-SHY', 'Shymkent', ['Shymkent']], ['KZ-KAR', 'Karaganda', ['Karaganda']], ['KZ-AKT', 'Aktobe', ['Aktobe']], ['KZ-ATY', 'Atyrau', ['Atyrau']], ['KZ-PAV', 'Pavlodar', ['Pavlodar']], ['KZ-VOS', 'East Kazakhstan', ['Oskemen']], ['KZ-KUS', 'Kostanay', ['Kostanay']], ['KZ-MAN', 'Mangystau', ['Aktau']], ['KZ-ZHA', 'Zhambyl', ['Taraz']]],
  UZ: [['UZ-SA', 'Samarkand', ['Samarkand']], ['UZ-BU', 'Bukhara', ['Bukhara']], ['UZ-AN', 'Andijan', ['Andijan']], ['UZ-FA', 'Fergana', ['Fergana']], ['UZ-NG', 'Namangan', ['Namangan']], ['UZ-QA', 'Kashkadarya', ['Karshi']], ['UZ-SU', 'Surkhandarya', ['Termez']], ['UZ-XO', 'Khorezm', ['Urgench']], ['UZ-NW', 'Navoiy', ['Navoiy']], ['UZ-QR', 'Karakalpakstan', ['Nukus']]],
};

export function expandRegionalCoverage(countries: Record<CountryId, Country>) {
  for (const [id, entries] of Object.entries(regionExpansions)) {
    const country = countries[id as CountryId];
    const reference = country.regions[0];
    const existing = new Set(country.regions.map(region => region.id));
    const added = entries!.filter(entry => !existing.has(entry[0]));
    country.regions.push(...makeRegions(added, country.legalBody, reference.statuteCitation, reference.salesTax,
      'Uses the existing national reference pack. Municipal charges, professional taxes, contribution bases and exemptions are not inferred from a location label. Enter applicable local amounts explicitly.'));
    country.regions.sort((a, b) => a.name.localeCompare(b.name, 'en'));
  }
  countries.IN.regionLabel = 'State / union territory';
  countries.DE.localityLabel = 'City / municipality';
  countries.JP.localityLabel = 'City / ward';
  countries.GB.localityLabel = 'City / local area';
  countries.AU.localityLabel = 'City / council area';
  countries.NZ.localityLabel = 'City / local area';

  for (const country of Object.values(countries)) {
    for (const region of country.regions) {
      if (!region.counties.length && region.cities.length) region.counties = localities(region.id, region.cities);
      if (region.id === 'OTHER') { region.customTax = true; region.referenceOnly = true; }
    }
    if (!country.regions.some(region => region.id === 'OTHER')) country.regions.push({
      id: 'OTHER', code: 'OTHER', name: 'Other region (custom estimate)', cities: [], counties: [], propertyTax: 0, salesTax: 0,
      medianIncome: 0, costOfLivingIndex: 0, taxStructure: 'Custom regional estimate', statuteCitation: 'No regional schedule loaded',
      governingBody: country.legalBody, description: 'The selected national reference still applies. Enter regional and local rates yourself; zero is an unset assumption, not a verified tax exemption.',
      customTax: true, referenceOnly: true,
    });
  }
}