/**
 * Documented current regional flags, keyed by `COUNTRY-REGION`.
 *
 * Only flags that are the current official banner of the jurisdiction are
 * mapped. Historical or unofficial banners are deliberately absent: where a
 * region has no distinct official flag, the renderer falls back to the
 * national flag of the sovereign state rather than inventing an emblem.
 */
export const regionFlagFiles: Record<string, { file: string; name: string }> = {
  // United States
  'US-CA': { file: 'Flag of California.svg', name: 'California' }, 'US-TX': { file: 'Flag of Texas.svg', name: 'Texas' },
  'US-NY': { file: 'Flag of New York.svg', name: 'New York' }, 'US-FL': { file: 'Flag of Florida.svg', name: 'Florida' },
  'US-WA': { file: 'Flag of Washington.svg', name: 'Washington' }, 'US-IL': { file: 'Flag of Illinois.svg', name: 'Illinois' },
  'US-CO': { file: 'Flag of Colorado.svg', name: 'Colorado' }, 'US-PA': { file: 'Flag of Pennsylvania.svg', name: 'Pennsylvania' },
  'US-OH': { file: 'Flag of Ohio.svg', name: 'Ohio' }, 'US-GA': { file: 'Flag of Georgia (U.S. state).svg', name: 'Georgia' },
  'US-NC': { file: 'Flag of North Carolina.svg', name: 'North Carolina' }, 'US-MA': { file: 'Flag of Massachusetts.svg', name: 'Massachusetts' },
  'US-MI': { file: 'Flag of Michigan.svg', name: 'Michigan' }, 'US-NJ': { file: 'Flag of New Jersey.svg', name: 'New Jersey' },
  'US-VA': { file: 'Flag of Virginia.svg', name: 'Virginia' }, 'US-AZ': { file: 'Flag of Arizona.svg', name: 'Arizona' },
  'US-MN': { file: 'Flag of Minnesota.svg', name: 'Minnesota' }, 'US-OR': { file: 'Flag of Oregon.svg', name: 'Oregon' },
  'US-UT': { file: 'Flag of Utah.svg', name: 'Utah' }, 'US-NV': { file: 'Flag of Nevada.svg', name: 'Nevada' },
  'US-MD': { file: 'Flag of Maryland.svg', name: 'Maryland' }, 'US-TN': { file: 'Flag of Tennessee.svg', name: 'Tennessee' },
  'US-CT': { file: 'Flag of Connecticut.svg', name: 'Connecticut' }, 'US-KY': { file: 'Flag of Kentucky.svg', name: 'Kentucky' },
  'US-MO': { file: 'Flag of Missouri.svg', name: 'Missouri' }, 'US-HI': { file: 'Flag of Hawaii.svg', name: 'Hawaii' },
  'US-AK': { file: 'Flag of Alaska.svg', name: 'Alaska' }, 'US-WI': { file: 'Flag of Wisconsin.svg', name: 'Wisconsin' },
  'US-SC': { file: 'Flag of South Carolina.svg', name: 'South Carolina' }, 'US-LA': { file: 'Flag of Louisiana.svg', name: 'Louisiana' },
  'US-DC': { file: 'Flag of the District of Columbia.svg', name: 'District of Columbia' },
  'US-OK': { file: 'Flag of Oklahoma.svg', name: 'Oklahoma' }, 'US-NM': { file: 'Flag of New Mexico.svg', name: 'New Mexico' },
  'US-ME': { file: 'Flag of Maine.svg', name: 'Maine' }, 'US-RI': { file: 'Flag of Rhode Island.svg', name: 'Rhode Island' },
  'US-DE': { file: 'Flag of Delaware.svg', name: 'Delaware' }, 'US-VT': { file: 'Flag of Vermont.svg', name: 'Vermont' },
  'US-NH': { file: 'Flag of New Hampshire.svg', name: 'New Hampshire' }, 'US-KS': { file: 'Flag of Kansas.svg', name: 'Kansas' },
  'US-IA': { file: 'Flag of Iowa.svg', name: 'Iowa' }, 'US-ID': { file: 'Flag of Idaho.svg', name: 'Idaho' },
  'US-AL': { file: 'Flag of Alabama.svg', name: 'Alabama' }, 'US-AR': { file: 'Flag of Arkansas.svg', name: 'Arkansas' },
  'US-IN': { file: 'Flag of Indiana.svg', name: 'Indiana' }, 'US-MS': { file: 'Flag of Mississippi.svg', name: 'Mississippi' },
  'US-MT': { file: 'Flag of Montana.svg', name: 'Montana' }, 'US-ND': { file: 'Flag of North Dakota.svg', name: 'North Dakota' },
  'US-SD': { file: 'Flag of South Dakota.svg', name: 'South Dakota' }, 'US-NE': { file: 'Flag of Nebraska.svg', name: 'Nebraska' },
  'US-WV': { file: 'Flag of West Virginia.svg', name: 'West Virginia' }, 'US-WY': { file: 'Flag of Wyoming.svg', name: 'Wyoming' },

  // Canada
  'CA-ON': { file: 'Flag of Ontario.svg', name: 'Ontario' }, 'CA-BC': { file: 'Flag of British Columbia.svg', name: 'British Columbia' },
  'CA-AB': { file: 'Flag of Alberta.svg', name: 'Alberta' }, 'CA-QC': { file: 'Flag of Quebec.svg', name: 'Quebec' },
  'CA-MB': { file: 'Flag of Manitoba.svg', name: 'Manitoba' }, 'CA-SK': { file: 'Flag of Saskatchewan.svg', name: 'Saskatchewan' },
  'CA-NS': { file: 'Flag of Nova Scotia.svg', name: 'Nova Scotia' }, 'CA-NB': { file: 'Flag of New Brunswick.svg', name: 'New Brunswick' },
  'CA-NL': { file: 'Flag of Newfoundland and Labrador.svg', name: 'Newfoundland and Labrador' },
  'CA-PE': { file: 'Flag of Prince Edward Island.svg', name: 'Prince Edward Island' },
  'CA-YT': { file: 'Flag of Yukon.svg', name: 'Yukon' }, 'CA-NT': { file: 'Flag of the Northwest Territories.svg', name: 'Northwest Territories' },
  'CA-NU': { file: 'Flag of Nunavut.svg', name: 'Nunavut' },

  // United Kingdom (Northern Ireland has no current official flag, so it falls back to the UK flag)
  'GB-ENG': { file: 'Flag of England.svg', name: 'England' }, 'GB-SCT': { file: 'Flag of Scotland.svg', name: 'Scotland' },
  'GB-WLS': { file: 'Flag of Wales.svg', name: 'Wales' },

  // Australia
  'AU-NSW': { file: 'Flag of New South Wales.svg', name: 'New South Wales' }, 'AU-VIC': { file: 'Flag of Victoria (Australia).svg', name: 'Victoria' },
  'AU-QLD': { file: 'Flag of Queensland.svg', name: 'Queensland' }, 'AU-WA': { file: 'Flag of Western Australia.svg', name: 'Western Australia' },
  'AU-SA': { file: 'Flag of South Australia.svg', name: 'South Australia' }, 'AU-TAS': { file: 'Flag of Tasmania.svg', name: 'Tasmania' },
  'AU-ACT': { file: 'Flag of the Australian Capital Territory.svg', name: 'Australian Capital Territory' },
  'AU-NT': { file: 'Flag of the Northern Territory.svg', name: 'Northern Territory' },

  // Germany
  'DE-BE': { file: 'Flag of Berlin.svg', name: 'Berlin' }, 'DE-BY': { file: 'Flag of Bavaria (lozengy).svg', name: 'Bavaria' },
  'DE-NW': { file: 'Flag of North Rhine-Westphalia.svg', name: 'North Rhine-Westphalia' }, 'DE-HH': { file: 'Flag of Hamburg.svg', name: 'Hamburg' },
  'DE-BW': { file: 'Flag of Baden-Württemberg.svg', name: 'Baden-Wurttemberg' }, 'DE-BB': { file: 'Flag of Brandenburg.svg', name: 'Brandenburg' },
  'DE-HB': { file: 'Flag of Bremen.svg', name: 'Bremen' }, 'DE-HE': { file: 'Flag of Hesse.svg', name: 'Hesse' },
  'DE-MV': { file: 'Flag of Mecklenburg-Western Pomerania.svg', name: 'Mecklenburg-Vorpommern' },
  'DE-NI': { file: 'Flag of Lower Saxony.svg', name: 'Lower Saxony' }, 'DE-RP': { file: 'Flag of Rhineland-Palatinate.svg', name: 'Rhineland-Palatinate' },
  'DE-SL': { file: 'Flag of Saarland.svg', name: 'Saarland' }, 'DE-SN': { file: 'Flag of Saxony.svg', name: 'Saxony' },
  'DE-ST': { file: 'Flag of Saxony-Anhalt (state).svg', name: 'Saxony-Anhalt' }, 'DE-SH': { file: 'Flag of Schleswig-Holstein.svg', name: 'Schleswig-Holstein' },
  'DE-TH': { file: 'Flag of Thuringia.svg', name: 'Thuringia' },

  // Japan
  'JP-TK': { file: 'Flag of Tokyo Metropolis.svg', name: 'Tokyo Metropolis' }, 'JP-OS': { file: 'Flag of Osaka Prefecture.svg', name: 'Osaka Prefecture' },
  'JP-KY': { file: 'Flag of Kyoto Prefecture.svg', name: 'Kyoto Prefecture' },
  'JP-01': { file: 'Flag of Hokkaido Prefecture.svg', name: 'Hokkaido' }, 'JP-04': { file: 'Flag of Miyagi Prefecture.svg', name: 'Miyagi' },
  'JP-13': { file: 'Flag of Tokyo Metropolis.svg', name: 'Tokyo' }, 'JP-14': { file: 'Flag of Kanagawa Prefecture.svg', name: 'Kanagawa' },
  'JP-23': { file: 'Flag of Aichi Prefecture.svg', name: 'Aichi' }, 'JP-28': { file: 'Flag of Hyogo Prefecture.svg', name: 'Hyogo' },
  'JP-40': { file: 'Flag of Fukuoka Prefecture.svg', name: 'Fukuoka' }, 'JP-47': { file: 'Flag of Okinawa Prefecture.svg', name: 'Okinawa' },

  // Switzerland
  'CH-ZH': { file: 'Flag of Canton of Zürich.svg', name: 'Canton of Zurich' }, 'CH-GE': { file: 'Flag of Canton of Geneva.svg', name: 'Canton of Geneva' },
  'CH-BE': { file: 'Flag of Canton of Bern.svg', name: 'Bern' }, 'CH-VD': { file: 'Flag of Canton of Vaud.svg', name: 'Vaud' },
  'CH-BS': { file: 'Flag of Canton of Basel-Stadt.svg', name: 'Basel-Stadt' }, 'CH-BL': { file: 'Flag of Canton of Basel-Landschaft.svg', name: 'Basel-Landschaft' },
  'CH-LU': { file: 'Flag of Canton of Lucerne.svg', name: 'Lucerne' }, 'CH-SG': { file: 'Flag of Canton of St. Gallen.svg', name: 'St. Gallen' },
  'CH-TI': { file: 'Flag of Canton of Ticino.svg', name: 'Ticino' }, 'CH-AG': { file: 'Flag of Canton of Aargau.svg', name: 'Aargau' },
  'CH-ZG': { file: 'Flag of Canton of Zug.svg', name: 'Zug' }, 'CH-VS': { file: 'Flag of Canton of Valais.svg', name: 'Valais' },
  'CH-FR': { file: 'Flag of Canton of Fribourg.svg', name: 'Fribourg' }, 'CH-NE': { file: 'Flag of Canton of Neuchâtel.svg', name: 'Neuchatel' },

  // Spain (autonomous communities)
  'ES-ES-MD': { file: 'Flag of the Community of Madrid.svg', name: 'Community of Madrid' }, 'ES-ES-CT': { file: 'Flag of Catalonia.svg', name: 'Catalonia' },
  'ES-ES-AN': { file: 'Flag of Andalucía.svg', name: 'Andalusia' }, 'ES-ES-AR': { file: 'Flag of Aragon.svg', name: 'Aragon' },
  'ES-ES-AS': { file: 'Flag of Asturias.svg', name: 'Asturias' }, 'ES-ES-IB': { file: 'Flag of the Balearic Islands.svg', name: 'Balearic Islands' },
  'ES-ES-PV': { file: 'Flag of the Basque Country.svg', name: 'Basque Country' }, 'ES-ES-CN': { file: 'Flag of the Canary Islands.svg', name: 'Canary Islands' },
  'ES-ES-CB': { file: 'Flag of Cantabria.svg', name: 'Cantabria' }, 'ES-ES-CM': { file: 'Flag of Castile-La Mancha.svg', name: 'Castilla-La Mancha' },
  'ES-ES-CL': { file: 'Flag of Castile and León.svg', name: 'Castile and Leon' }, 'ES-ES-EX': { file: 'Flag of Extremadura (with coat of arms).svg', name: 'Extremadura' },
  'ES-ES-GA': { file: 'Flag of Galicia.svg', name: 'Galicia' }, 'ES-ES-RI': { file: 'Flag of La Rioja (with coat of arms).svg', name: 'La Rioja' },
  'ES-ES-MC': { file: 'Flag of the Region of Murcia.svg', name: 'Murcia' }, 'ES-ES-NC': { file: 'Flag of Navarre.svg', name: 'Navarre' },
  'ES-ES-VC': { file: 'Flag of the Land of Valencia (custom).svg', name: 'Valencian Community' },

  // Italy (regions)
  'IT-IT-LAZ': { file: 'Flag of Lazio.svg', name: 'Lazio' }, 'IT-IT-LOM': { file: 'Flag of Lombardy.svg', name: 'Lombardy' },
  'IT-IT-ABR': { file: 'Flag of Abruzzo.svg', name: 'Abruzzo' }, 'IT-IT-BAS': { file: 'Flag of Basilicata.svg', name: 'Basilicata' },
  'IT-IT-CAL': { file: 'Flag of Calabria.svg', name: 'Calabria' }, 'IT-IT-CAM': { file: 'Flag of Campania.svg', name: 'Campania' },
  'IT-IT-EMR': { file: 'Flag of Emilia-Romagna.svg', name: 'Emilia-Romagna' }, 'IT-IT-FVG': { file: 'Flag of Friuli-Venezia Giulia.svg', name: 'Friuli-Venezia Giulia' },
  'IT-IT-LIG': { file: 'Flag of Liguria.svg', name: 'Liguria' }, 'IT-IT-MAR': { file: 'Flag of Marche.svg', name: 'Marche' },
  'IT-IT-MOL': { file: 'Flag of Molise.svg', name: 'Molise' }, 'IT-IT-PMN': { file: 'Flag of Piedmont.svg', name: 'Piedmont' },
  'IT-IT-PUG': { file: 'Flag of Apulia.svg', name: 'Apulia' }, 'IT-IT-SAR': { file: 'Flag of Sardinia, Italy.svg', name: 'Sardinia' },
  'IT-IT-SIC': { file: 'Flag of Sicily.svg', name: 'Sicily' }, 'IT-IT-TOS': { file: 'Flag of Tuscany.svg', name: 'Tuscany' },
  'IT-IT-UMB': { file: 'Flag of Umbria.svg', name: 'Umbria' }, 'IT-IT-VDA': { file: "Flag of Aosta Valley.svg", name: 'Aosta Valley' },
  'IT-IT-VEN': { file: 'Flag of Veneto.svg', name: 'Veneto' },

  // Mexico, Brazil, Argentina
  'MX-MX-CDMX': { file: 'Flag of Mexico City.svg', name: 'Mexico City' }, 'MX-MX-NL': { file: 'Flag of Nuevo León.svg', name: 'Nuevo Leon' },
  'MX-MX-JAL': { file: 'Flag of Jalisco.svg', name: 'Jalisco' }, 'MX-MX-YUC': { file: 'Flag of Yucatán.svg', name: 'Yucatan' },
  'MX-MX-BCN': { file: 'Flag of Baja California.svg', name: 'Baja California' }, 'MX-MX-CHH': { file: 'Flag of Chihuahua.svg', name: 'Chihuahua' },
  'BR-BR-SP': { file: 'Bandeira do estado de São Paulo.svg', name: 'Sao Paulo' }, 'BR-BR-RJ': { file: 'Bandeira do estado do Rio de Janeiro.svg', name: 'Rio de Janeiro' },
  'BR-BR-MG': { file: 'Bandeira de Minas Gerais.svg', name: 'Minas Gerais' }, 'BR-BR-BA': { file: 'Bandeira da Bahia.svg', name: 'Bahia' },
  'BR-BR-RS': { file: 'Bandeira do Rio Grande do Sul.svg', name: 'Rio Grande do Sul' }, 'BR-BR-PR': { file: 'Bandeira do Paraná.svg', name: 'Parana' },
  'BR-BR-DF': { file: 'Bandeira do Distrito Federal (Brasil).svg', name: 'Federal District' },
  'AR-AR-CABA': { file: 'Bandera de la Ciudad de Buenos Aires.svg', name: 'Buenos Aires City' },
  'AR-AR-BA': { file: 'Flag of Buenos Aires Province.svg', name: 'Buenos Aires Province' },
  'AR-AR-CBA': { file: 'Bandera de la Provincia de Córdoba.svg', name: 'Cordoba' },

  // Rest of world
  'KR-KR-SE': { file: 'Flag of Seoul.svg', name: 'Seoul' },
  'NL-NL-NH': { file: 'Flag of North Holland.svg', name: 'North Holland' }, 'NL-NL-ZH': { file: 'Flag of South Holland.svg', name: 'South Holland' },
  'NL-NL-UT': { file: 'Flag of Utrecht (province).svg', name: 'Utrecht' }, 'NL-NL-NB': { file: 'Flag of North Brabant.svg', name: 'North Brabant' },
  'NL-NL-GE': { file: 'Flag of Gelderland.svg', name: 'Gelderland' }, 'NL-NL-FR': { file: 'Flag of Friesland.svg', name: 'Friesland' },
  'NL-NL-LI': { file: 'Flag of Limburg (Netherlands).svg', name: 'Limburg' }, 'NL-NL-GR': { file: 'Flag of Groningen (province).svg', name: 'Groningen' },
  'ID-ID-JK': { file: 'Flag of Jakarta (vectorised).svg', name: 'Jakarta' },
  'TH-TH-BKK': { file: 'Flag of Bangkok.svg', name: 'Bangkok' },
  'PH-PH-NCR': { file: 'Seal of Metro Manila.svg', name: 'Metro Manila' },
  'ZA-ZA-GP': { file: 'Flag of Gauteng Province.svg', name: 'Gauteng' }, 'ZA-ZA-WC': { file: 'Flag of the Western Cape.svg', name: 'Western Cape' },
  'ZA-ZA-KZN': { file: 'Flag of KwaZulu-Natal Province.svg', name: 'KwaZulu-Natal' }, 'ZA-ZA-EC': { file: 'Flag of the Eastern Cape.svg', name: 'Eastern Cape' },
  'AE-AE-DXB': { file: 'Flag of Dubai.svg', name: 'Dubai' }, 'AE-AE-AUH': { file: 'Flag of Abu Dhabi.svg', name: 'Abu Dhabi' },
  'AE-AE-SHJ': { file: 'Flag of Sharjah.svg', name: 'Sharjah' }, 'AE-AE-AJM': { file: 'Flag of Ajman.svg', name: 'Ajman' },
  'AE-AE-RAK': { file: 'Flag of Ras al Khaimah.svg', name: 'Ras Al Khaimah' }, 'AE-AE-FUJ': { file: 'Flag of Fujairah.svg', name: 'Fujairah' },
  'AE-AE-UAQ': { file: 'Flag of Umm al-Quwain.svg', name: 'Umm Al Quwain' },
  'PL-PL-MAZ': { file: 'POL województwo mazowieckie flag.svg', name: 'Mazovia' },
  'PL-PL-DS': { file: 'POL województwo dolnośląskie flag.svg', name: 'Lower Silesia' },
  'PL-PL-MA': { file: 'POL województwo małopolskie flag.svg', name: 'Lesser Poland' },
  'PL-PL-SL': { file: 'POL województwo śląskie flag.svg', name: 'Silesia' },
  'PL-PL-WP': { file: 'POL województwo wielkopolskie flag.svg', name: 'Greater Poland' },
  'PL-PL-PM': { file: 'POL województwo pomorskie flag.svg', name: 'Pomerania' },
  'SE-SE-STH': { file: 'Flag of Stockholm.svg', name: 'Stockholm' },
  'SE-SE-VG': { file: 'Flag of Västra Götaland County.svg', name: 'Vastra Gotaland' },
  'SE-SE-SK': { file: 'Flag of Scania.svg', name: 'Skane' },
  'HK-HK-HK': { file: 'Flag of Hong Kong.svg', name: 'Hong Kong' },
  'TW-TW-TPE': { file: 'Flag of Taipei City.svg', name: 'Taipei' }, 'TW-TW-KHH': { file: 'Flag of Kaohsiung City.svg', name: 'Kaohsiung' },
  'PR-PR-SJ': { file: 'Flag of Puerto Rico.svg', name: 'Puerto Rico' },
  'PT-PT-LIS': { file: 'Flag of Lisbon.svg', name: 'Lisbon' }, 'PT-PT-POR': { file: 'Flag of Porto.svg', name: 'Porto' },
  'PT-PT-30': { file: 'Flag of Madeira.svg', name: 'Madeira' }, 'PT-PT-20': { file: 'Flag of the Azores.svg', name: 'Azores' },
  'BE-BE-VLG': { file: 'Flag of Flanders.svg', name: 'Flanders' }, 'BE-BE-WAL': { file: 'Flag of Wallonia.svg', name: 'Wallonia' },
  'BE-BE-BRU': { file: 'Flag of the Brussels-Capital Region.svg', name: 'Brussels' },
  'BE-BE-VAN': { file: 'Flag of Antwerp Province.svg', name: 'Antwerp' }, 'BE-BE-WLG': { file: 'Flag of Liège Province.svg', name: 'Liege' },
  'AT-AT-W': { file: 'Flag of Wien (state).svg', name: 'Vienna' }, 'AT-AT-6': { file: 'Flag of Styria (state).svg', name: 'Styria' },
  'AT-AT-7': { file: 'Flag of Tyrol (state).svg', name: 'Tyrol' }, 'AT-AT-5': { file: 'Flag of Salzburg (state).svg', name: 'Salzburg' },
  'AT-AT-4': { file: 'Flag of Upper Austria.svg', name: 'Upper Austria' }, 'AT-AT-2': { file: 'Flag of Carinthia (state).svg', name: 'Carinthia' },
  'NO-NO-03': { file: 'Flag of Oslo.svg', name: 'Oslo' },
  'CL-CL-RM': { file: 'Flag of the Santiago Metropolitan Region, Chile.svg', name: 'Santiago Metropolitan' },
  'RU-RU-MOW': { file: 'Flag of Moscow.svg', name: 'Moscow' }, 'RU-RU-SPE': { file: 'Flag of Saint Petersburg.svg', name: 'Saint Petersburg' },
  'RU-RU-TA': { file: 'Flag of Tatarstan.svg', name: 'Tatarstan' }, 'RU-RU-BA': { file: 'Flag of Bashkortostan.svg', name: 'Bashkortostan' },
  'IN-IN-DL': { file: 'Flag of Delhi.svg', name: 'Delhi' },
  'GB-GB-ENG': { file: 'Flag of England.svg', name: 'England' },
  'CN-CN-HK': { file: 'Flag of Hong Kong.svg', name: 'Hong Kong' }, 'CN-CN-MO': { file: 'Flag of Macau.svg', name: 'Macao' },
};
