import { internalHref } from "./urls";
import { presetHref } from "./presets";

export type Guide = {
  slug: string;
  title: string;
  description: string;
  category: "Conversions" | "Calculation methods" | "Reference information";
  formula: string;
  takeaway: string;
  imageAlt: string;
  intro: string;
  sections: { heading: string; paragraphs: string[] }[];
  table: { caption: string; columns: string[]; rows: string[][] };
  toolHref: string;
  toolLabel: string;
  related: string[];
};

// Curated, distinct explanatory pages — not generated permutations of keywords
// or user query parameters. Worked figures are illustrative and clearly labelled.
export const GUIDES: Guide[] = [
  {
    slug: "meters-to-feet",
    title: "How to Convert Meters to Feet (Formula & Table)",
    description: "Convert meters to feet using the exact definition of a foot. Includes a worked 5-meter example, a reference table and a ready-to-use converter.",
    category: "Conversions",
    formula: "feet = meters ÷ 0.3048",
    takeaway: "1 meter ≈ 3.280839895 feet",
    imageAlt: "Meter-to-foot conversion diagram: divide the length in meters by 0.3048 to obtain feet.",
    intro: "A meter and a foot both measure length. The international foot is defined as exactly 0.3048 meters, so converting meters to feet means dividing by 0.3048. The definition is exact; a displayed decimal answer may be rounded.",
    sections: [
      { heading: "Work through a five-meter example", paragraphs: ["Start with 5 meters. Divide 5 by 0.3048 to obtain 16.404199475… feet. Rounded to six decimal places, the result is 16.404199 feet. Keep more digits for intermediate calculations and round only the final answer.", "To verify the direction, multiply the foot value by 0.3048. It should return approximately 5 meters, with any small difference caused by rounding."] },
      { heading: "Decimal feet are not feet and inches", paragraphs: ["The decimal part of a foot is a fraction of 12 inches. For example, 5.5 feet means 5 feet and 6 inches, not 5 feet and 5 inches. To split a result, take its whole feet and multiply the remaining fraction by 12."] },
      { heading: "Use the converter", paragraphs: ["The linked converter starts at 5 meters with feet as the target. Change the amount if needed and press Convert. Opening the tool or changing its inputs does not automatically reveal a calculated result.", "Do not use the length factor for area or volume. Square feet require the factor squared, and cubic feet require the factor cubed."] },
    ],
    table: { caption: "Illustrative lengths, feet rounded to six decimal places", columns: ["Meters", "Feet"], rows: [["1", "3.280840"], ["5", "16.404199"], ["10", "32.808399"], ["100", "328.083990"]] },
    toolHref: internalHref("/tools/units", { category: "length", from: "m", to: "ft", value: "5" }),
    toolLabel: "Open meters-to-feet converter",
    related: ["pounds-to-kilograms", "celsius-to-fahrenheit"],
  },
  {
    slug: "celsius-to-fahrenheit",
    title: "Celsius to Fahrenheit: °C to °F Formula & Examples",
    description: "Convert Celsius to Fahrenheit with °F = °C × 9/5 + 32. See common temperatures, the inverse formula and the difference between temperatures and changes.",
    category: "Conversions",
    formula: "°F = °C × 9/5 + 32",
    takeaway: "20 °C = 68 °F",
    imageAlt: "Temperature conversion diagram: multiply Celsius by nine fifths, then add thirty-two for Fahrenheit.",
    intro: "Temperature scales have different zero points as well as different step sizes. That is why converting a Celsius temperature to Fahrenheit requires both multiplication and an offset, rather than a single conversion factor.",
    sections: [
      { heading: "Convert 20 °C step by step", paragraphs: ["Multiply 20 by 9/5 to obtain 36. Add 32, giving 68 °F. For the reverse direction, subtract 32 from Fahrenheit first, then multiply by 5/9. Thus (68 − 32) × 5/9 returns 20 °C."] },
      { heading: "A temperature change is different", paragraphs: ["For a change or difference in temperature, do not add 32. A rise of 10 Celsius degrees is a rise of 18 Fahrenheit degrees. The offset is only needed when converting an actual temperature reading.", "Celsius to kelvin uses K = °C + 273.15. In ordinary thermodynamic use, a temperature below 0 K is not physically valid. Check the meaning of the reading before using a result."] },
      { heading: "Convert a reading", paragraphs: ["Open the converter, enter the reading, choose Celsius and Fahrenheit, and press Convert. The initial example is 20 °C. You can swap the scales to check the reverse calculation.", "Numerical conversion does not account for sensor calibration, uncertainty or a safety limit. Those require information about the particular instrument and situation."] },
    ],
    table: { caption: "Illustrative absolute temperatures", columns: ["Celsius", "Fahrenheit"], rows: [["−40 °C", "−40 °F"], ["0 °C", "32 °F"], ["20 °C", "68 °F"], ["37 °C", "98.6 °F"], ["100 °C", "212 °F"]] },
    toolHref: internalHref("/tools/units", { category: "temperature", from: "C", to: "F", value: "20" }),
    toolLabel: "Open temperature converter",
    related: ["meters-to-feet", "pounds-to-kilograms"],
  },
  {
    slug: "pounds-to-kilograms",
    title: "LBS to KG: Pounds to Kilograms Formula & Table",
    description: "Convert pounds to kilograms with the exact factor 0.45359237. Follow a 10-pound example and use the prefilled mass converter.",
    category: "Conversions",
    formula: "kilograms = pounds × 0.45359237",
    takeaway: "10 lb = 4.5359237 kg",
    imageAlt: "Pound-to-kilogram conversion diagram using the factor 0.45359237.",
    intro: "The international avoirdupois pound is defined as exactly 0.45359237 kilograms. Multiply a mass in pounds by this value to express it in kilograms. Divide by the same value for the reverse conversion.",
    sections: [
      { heading: "Convert ten pounds", paragraphs: ["Multiply 10 × 0.45359237. The result is 4.5359237 kg. If you only need two decimal places, report 4.54 kg; keep the full value while performing further arithmetic.", "The often-quoted 2.2 pounds per kilogram is a useful estimate, not the exact inverse. Using it repeatedly can accumulate avoidable rounding differences."] },
      { heading: "Mass is not force", paragraphs: ["This conversion is between mass units. It is not a conversion from pounds-force to newtons. Similarly, the ounce in the mass category is an avoirdupois ounce, not a fluid ounce or a troy ounce."] },
      { heading: "Use the mass converter", paragraphs: ["The link below sets the converter to 10 lb and kg. Press Convert to reveal your result. Try a different value or swap the units to reverse the direction.", "Exact unit definitions do not make the original measurement exact. The precision of a scale and its calibration still limit the useful precision of a converted reading."] },
    ],
    table: { caption: "Illustrative pound-to-kilogram values", columns: ["Pounds", "Kilograms"], rows: [["1", "0.45359237"], ["5", "2.26796185"], ["10", "4.5359237"], ["100", "45.359237"]] },
    toolHref: internalHref("/tools/units", { category: "mass", from: "lb", to: "kg", value: "10" }),
    toolLabel: "Open pounds-to-kilograms converter",
    related: ["meters-to-feet", "celsius-to-fahrenheit"],
  },
  {
    slug: "megabytes-vs-mebibytes",
    title: "MB vs MiB: Decimal vs Binary Data Sizes Explained",
    description: "Understand why a megabyte differs from a mebibyte. Compare bytes, MB and MiB, then convert decimal and binary storage sizes.",
    category: "Conversions",
    formula: "MiB = MB × 1,000,000 ÷ 1,048,576",
    takeaway: "1 MiB = 1.048576 MB",
    imageAlt: "Comparison of a decimal megabyte, one million bytes, and a binary mebibyte, 1,048,576 bytes.",
    intro: "MB and MiB describe different quantities. A megabyte (MB) is 1,000,000 bytes. A mebibyte (MiB) is 1,048,576 bytes, or 2²⁰ bytes. Explicit unit labels avoid treating these two conventions as interchangeable.",
    sections: [
      { heading: "Convert between decimal and binary", paragraphs: ["To convert MB to MiB, multiply by 1,000,000 and divide by 1,048,576. One MB is exactly 0.95367431640625 MiB. In the other direction, one MiB is exactly 1.048576 MB.", "For example, 500 MB is approximately 476.837158 MiB. The number changes because the unit size changes, not because any bytes have disappeared."] },
      { heading: "Keep bits and bytes separate", paragraphs: ["A byte contains eight bits. Uppercase B means bytes; lowercase b generally means bits. A network rate in megabits per second is not the same as a file size in megabytes, and a transfer-time estimate must also allow for overhead and real throughput."] },
      { heading: "Check how your device labels capacity", paragraphs: ["Storage packaging, operating systems and applications do not always use the same convention. Compare the underlying byte count where possible instead of assuming what a displayed abbreviation means.", "The data converter labels both conventions explicitly. The linked example is 500 MB to MiB; press Convert to reveal the result."] },
    ],
    table: { caption: "Definitions of common data-size units", columns: ["Unit", "Bytes"], rows: [["1 kB", "1,000"], ["1 KiB", "1,024"], ["1 MB", "1,000,000"], ["1 MiB", "1,048,576"], ["1 GB", "1,000,000,000"], ["1 GiB", "1,073,741,824"]] },
    toolHref: internalHref("/tools/units", { category: "data", from: "MB", to: "MiB", value: "500" }),
    toolLabel: "Open decimal-to-binary converter",
    related: ["meters-to-feet", "solve-linear-systems"],
  },
  {
    slug: "compound-interest",
    title: "Compound interest: formula, assumptions and worked example",
    description: "Explore P(1 + r/n)^(nt) with a worked monthly-compounding example. Learn rate conventions and assumptions, then open the formula with values already filled in.",
    category: "Calculation methods",
    formula: "A = P × (1 + r/n)^(n × t)",
    takeaway: "An illustration of fixed-rate growth",
    imageAlt: "Compound interest equation showing principal, annual rate, compounding frequency and time.",
    intro: "Compound interest adds interest to a balance so future interest is calculated on a larger amount. The expression A = P × (1 + r/n)^(n × t) describes fixed-rate growth with equal compounding periods and no extra deposits or withdrawals.",
    sections: [
      { heading: "Define the inputs", paragraphs: ["P is the starting principal. The nominal annual rate r is written as a decimal, so 5% becomes 0.05. The number n is compounding periods per year, and t is elapsed time in years. Monthly compounding uses n = 12.", "Do not substitute an effective annual yield for a nominal annual rate without adjusting the formula. They are different measures."] },
      { heading: "Work through the illustration", paragraphs: ["Set P = 1000, r = 0.05, n = 12 and t = 10. The monthly rate is 0.05/12 and there are 120 periods. The calculation gives approximately 1647.00949769, or 1647.01 rounded to two decimal places.", "The illustrative increase is the final amount minus the starting principal, about 647.01. This is a mathematical example, not a forecast or a product quote."] },
      { heading: "What this formula leaves out", paragraphs: ["Fees, tax, inflation, changing rates, rounding per payment period and additional contributions are not included. The timing of deposits also matters. Use a model that matches the actual schedule for a real decision.", "Open the prefilled formula and press Evaluate. Saving is optional; selecting this example does not submit or save anything by itself."] },
    ],
    table: { caption: "Inputs for the worked illustration", columns: ["Symbol", "Meaning", "Value"], rows: [["P", "Starting principal", "1000"], ["r", "Nominal annual rate", "0.05"], ["n", "Periods each year", "12"], ["t", "Years", "10"], ["A", "Illustrative final amount", "1647.01 (rounded)"]] },
    toolHref: presetHref("compound-interest"), toolLabel: "Open compound-interest example",
    related: ["solve-linear-systems", "exchange-rate-reference-values"],
  },
  {
    slug: "solve-linear-systems",
    title: "Solving Two Linear Equations: Ax = b, Worked",
    description: "Write two equations as Ax = b, solve a small matrix system and verify both residuals. Open the example in the scientific calculator.",
    category: "Calculation methods",
    formula: "A × x = b",
    takeaway: "2x + y = 5; x − y = 1 → x = 2, y = 1",
    imageAlt: "Matrix representation of two linear equations with the solution x equals two and y equals one.",
    intro: "A linear system can be written as a coefficient matrix multiplied by an unknown vector. This makes the relationship between equations explicit and allows the solution to be checked by substituting it back into every original equation.",
    sections: [
      { heading: "Build the coefficient matrix", paragraphs: ["For 2x + y = 5 and x − y = 1, the coefficient rows are [2, 1] and [1, −1]. The right-hand side is the column [5, 1]. Keep the order of unknowns identical in both rows.", "In the calculator, semicolons separate matrix rows. Enter lusolve([2, 1; 1, -1], [5; 1]) and press Calculate. The returned column [[2], [1]] corresponds to x = 2 and y = 1."] },
      { heading: "Verify rather than assume", paragraphs: ["Substitute the result into both equations: 2 × 2 + 1 = 5 and 2 − 1 = 1. Each left side matches its right side, so both residuals are zero for this example.", "A small residual can help check a computed answer, but it does not by itself prove that a poorly conditioned system has an accurate solution."] },
      { heading: "Understand the limitations", paragraphs: ["A singular coefficient matrix does not have a unique solution. Nearly dependent equations can also amplify measurement or rounding errors. Do not assume every matrix can be inverted or every linear system has one answer.", "Use consistent units and retain enough input precision. For larger or safety-critical work, compare with an independently verified method."] },
    ],
    table: { caption: "Substitution check for the worked example", columns: ["Equation", "Substitute x = 2, y = 1", "Residual"], rows: [["2x + y = 5", "2 × 2 + 1 − 5", "0"], ["x − y = 1", "2 − 1 − 1", "0"]] },
    toolHref: presetHref("linear-system", "scientific"), toolLabel: "Open the linear-system example",
    related: ["compound-interest", "megabytes-vs-mebibytes"],
  },
  {
    slug: "exchange-rate-reference-values",
    title: "Currency Reference Rates vs Dealing Rates: Why They Differ",
    description: "Learn why a currency conversion can differ from a bank or card quote. Understand reference dates, rates, spreads, fees and a simple worked illustration.",
    category: "Reference information",
    formula: "converted amount = amount × rate",
    takeaway: "A reference value is not a dealing quote",
    imageAlt: "Currency conversion diagram showing an amount multiplied by a reference rate, with fees and timing considered separately.",
    intro: "A currency reference rate is an informational value for a particular date or period. It is not a promise that a bank, card issuer or exchange will offer the same price. A displayed conversion is only as current and applicable as the underlying rate.",
    sections: [
      { heading: "Check the direction of the rate", paragraphs: ["If a rate is expressed as target units per one base unit, multiply the base amount by that rate. As an illustration only, an amount of 100 multiplied by a rate of 0.90 gives 90 target units. This is not a current market quote.", "For the opposite direction, use the corresponding inverse rate rather than multiplying by the same number. Rounding an inverse before calculation can slightly change the result."] },
      { heading: "Why your transaction may differ", paragraphs: ["The exchange spread, fixed fees, percentage fees, settlement time and card conversion rules can all affect the final amount. A page receipt time is also different from the date of the rate itself.", "In the currency tool, inspect the reference date after pressing Convert. A background refresh does not mean the underlying source has published a newer reference value."] },
      { heading: "Use reference figures carefully", paragraphs: ["The linked tool opens with 100 USD and EUR as the target. Press Convert when the reference information is ready. Confirm any financial decision with the relevant transaction provider and account for all charges.", "Rate history is context, not a prediction. Missing dates or delayed updates should not be interpreted as unchanged market conditions."] },
    ],
    table: { caption: "Illustration only — not current market data", columns: ["Item", "Illustrative value"], rows: [["Base amount", "100"], ["Target units per base unit", "0.90"], ["Before charges", "90"], ["Fixed target-currency fee", "2"], ["After that illustrative fee", "88"]] },
    toolHref: internalHref("/tools/currency", { base: "USD", to: "EUR", amount: "100" }), toolLabel: "Open the currency reference tool",
    related: ["compound-interest", "meters-to-feet"],
  },
  {
    slug: "miles-to-kilometers",
    title: "Miles to Kilometers: mi to km Conversion",
    description: "Convert miles to kilometers with the exact international-mile definition. Includes a worked 5-mile example, a reference table and an editable converter.",
    category: "Conversions",
    formula: "kilometers = miles × 1.609344",
    takeaway: "5 mi = 8.04672 km",
    imageAlt: "Miles converted to kilometers using the exact factor 1.609344.",
    intro: "The international mile is defined as exactly 1.609344 kilometers. Multiply a distance in miles by this factor to express it in kilometers. The factor is exact; the precision of the distance you measured may not be.",
    sections: [
      { heading: "Calculate five miles", paragraphs: ["Multiply 5 by 1.609344 to get 8.04672 km. For a route-planning estimate you might round to 8.05 km, but keep the unrounded value if it will feed into another calculation.", "A fast inverse check is to divide the kilometer result by 1.609344. The answer returns to 5 miles, subject only to the displayed rounding."] },
      { heading: "Choose the mile you mean", paragraphs: ["This page uses the international statute mile, not a nautical mile. A nautical mile is longer and is used for navigation and aviation contexts. Check the unit label before comparing two distances.", "Area and volume use squared or cubed factors. Multiplying a square-mile value by the length factor once will not convert it to square kilometers."] },
      { heading: "Convert your own distance", paragraphs: ["The linked unit converter opens at 5 miles to kilometers. Change the amount or select another unit pair, then press Convert to reveal the result.", "A conversion changes the unit, not the uncertainty of the original measurement or the distance along a particular route."] },
    ],
    table: { caption: "Illustrative miles converted to kilometers", columns: ["Miles", "Kilometers"], rows: [["1", "1.609344"], ["5", "8.04672"], ["10", "16.09344"], ["100", "160.9344"]] },
    toolHref: internalHref("/tools/units", { category: "length", from: "mi", to: "km", value: "5" }),
    toolLabel: "Open miles-to-kilometers converter",
    related: ["meters-to-feet", "kilometers-per-hour-to-mph"],
  },
  {
    slug: "kilometers-per-hour-to-mph",
    title: "Km/h to MPH: Speed Conversion Explained",
    description: "Convert km/h to mph by multiplying by the exact speed ratio. See a worked 100 km/h example and open the speed converter with inputs ready.",
    category: "Conversions",
    formula: "mph = km/h × 0.621371192237334…",
    takeaway: "100 km/h ≈ 62.1371 mph",
    imageAlt: "Speed conversion from kilometers per hour to miles per hour using the mile and kilometer definitions.",
    intro: "Speed is distance divided by time. To convert kilometers per hour to miles per hour, convert the distance unit while keeping the hour unchanged. One kilometer per hour is approximately 0.621371 miles per hour.",
    sections: [
      { heading: "Work through 100 km/h", paragraphs: ["Multiply 100 km/h by 0.621371192237334…. The result is approximately 62.137119 mph, commonly rounded to 62.14 mph.", "For the reverse conversion, divide miles per hour by the same factor, or multiply by approximately 1.609344. Do not apply the ratio to a distance-only value or to a time interval."] },
      { heading: "Respect measurement and context", paragraphs: ["A converted speed does not account for a vehicle display's tolerance, sensor calibration, changing speed or local rules. It simply expresses the same numerical speed in different units.", "The long decimal is a conversion factor, not a claim that a real-world speedometer is accurate to that many decimal places."] },
      { heading: "Use the speed converter", paragraphs: ["The linked tool is set to 100 km/h and mph. Change the input if needed and press Convert to reveal the answer."] },
    ],
    table: { caption: "Illustrative speeds converted from km/h to mph", columns: ["km/h", "mph"], rows: [["30", "18.6411"], ["50", "31.0686"], ["100", "62.1371"], ["120", "74.5647"]] },
    toolHref: internalHref("/tools/units", { category: "speed", from: "km/h", to: "mph", value: "100" }),
    toolLabel: "Open km/h-to-mph converter",
    related: ["miles-to-kilometers", "meters-to-feet"],
  },
  {
    slug: "liters-to-us-gallons",
    title: "Liters to Gallons: US vs Imperial, Explained",
    description: "Convert liters to US liquid gallons using the exact US-gallon definition. See why US and Imperial gallons differ and try a prefilled volume converter.",
    category: "Conversions",
    formula: "US gallons = liters ÷ 3.785411784",
    takeaway: "10 L ≈ 2.64172 US gal",
    imageAlt: "Volume conversion from liters to US liquid gallons using 3.785411784 liters per gallon.",
    intro: "Volume conversions depend on which gallon is meant. One US liquid gallon is exactly 3.785411784 liters. The Imperial gallon used in the United Kingdom is a different, larger unit.",
    sections: [
      { heading: "Convert ten liters", paragraphs: ["Divide 10 by 3.785411784 to obtain about 2.64172052 US gallons. Rounded to five decimal places, that is 2.64172 US gal.", "To convert US gallons to liters, multiply by 3.785411784. Keeping the direction visible helps avoid accidentally multiplying when you should divide."] },
      { heading: "US and Imperial gallons are different", paragraphs: ["One Imperial gallon is 4.54609 liters. A recipe, vehicle specification or container marked only ‘gallon’ can therefore be ambiguous when units cross regions. Look for US, Imperial or UK in the label.", "A fluid ounce is also a volume unit; an ounce in a mass conversion is not interchangeable with it."] },
      { heading: "Convert a volume", paragraphs: ["The linked tool opens at 10 liters to US gallons. Confirm the selected unit label, change the value if necessary, then press Convert to reveal the result."] },
    ],
    table: { caption: "Illustrative liters converted to US liquid gallons", columns: ["Liters", "US gallons"], rows: [["1", "0.264172"], ["5", "1.320860"], ["10", "2.641721"], ["20", "5.283441"]] },
    toolHref: internalHref("/tools/units", { category: "volume", from: "l", to: "gal_us", value: "10" }),
    toolLabel: "Open liters-to-US-gallons converter",
    related: ["megabytes-vs-mebibytes", "pounds-to-kilograms"],
  },
  {
    slug: "quadratic-equation-positive-root",
    title: "The Quadratic Formula, Solved Step by Step",
    description: "Use the quadratic formula with a, b and c inputs. Work through x² − 5x + 6 = 0, understand the discriminant and load the positive root example.",
    category: "Calculation methods",
    formula: "x = (−b ± √(b² − 4ac)) / (2a)",
    takeaway: "x² − 5x + 6 = 0 has roots 2 and 3",
    imageAlt: "Quadratic formula showing the two possible roots from the plus and minus branches.",
    intro: "A quadratic equation has the form ax² + bx + c = 0, where a is not zero. The quadratic formula provides two candidate roots. The symbol ± means calculate one result with plus and a second result with minus.",
    sections: [
      { heading: "Calculate the example", paragraphs: ["For x² − 5x + 6 = 0, use a = 1, b = −5 and c = 6. The discriminant b² − 4ac is 25 − 24 = 1. The plus branch gives (5 + 1)/2 = 3; the minus branch gives (5 − 1)/2 = 2.", "The preset in the formula tool evaluates the plus branch. Change the plus sign to minus to calculate the other root, then press Evaluate to show each result."] },
      { heading: "Interpret the discriminant", paragraphs: ["A positive discriminant gives two distinct real roots. A zero discriminant gives one repeated real root. A negative discriminant gives complex roots when the expression tool is configured to handle complex values.", "If a = 0, the equation is not quadratic and the formula divides by zero. Check a before applying the formula."] },
      { heading: "Verify by substitution", paragraphs: ["Substitute x = 2: 2² − 5(2) + 6 = 0. Substitute x = 3: 3² − 5(3) + 6 = 0. Both results satisfy the original equation.", "Verification catches sign errors and helps distinguish a root calculation from a result that merely looks plausible."] },
    ],
    table: { caption: "Quadratic example inputs and roots", columns: ["Coefficient / value", "Value"], rows: [["a", "1"], ["b", "−5"], ["c", "6"], ["Discriminant", "1"], ["Minus root", "2"], ["Plus root", "3"]] },
    toolHref: presetHref("quadratic-root"),
    toolLabel: "Open the quadratic positive-root example",
    related: ["solve-linear-systems", "compound-interest"],
  },
  {
    slug: "square-feet-to-square-meters",
    title: "Square Feet to Square Meters: ft² to m²",
    description: "Convert area from square feet to square meters using the defined foot length squared. Includes a 500-square-foot example and a prefilled converter.",
    category: "Conversions",
    formula: "m² = ft² × 0.09290304",
    takeaway: "500 ft² = 46.45152 m²",
    imageAlt: "Area conversion showing a square-foot measurement converted to square meters with the squared length factor.",
    intro: "Area is two-dimensional, so its conversion factor is the square of the length factor. Since one international foot is exactly 0.3048 meters, one square foot is 0.3048² = 0.09290304 square meters.",
    sections: [
      { heading: "Convert 500 square feet", paragraphs: ["Multiply 500 by 0.09290304 to obtain 46.45152 m². If an estimate to one decimal place is enough, this is about 46.5 m².", "Do not multiply by 0.3048 just once. That is the length factor; area needs the factor squared. Volume uses the length factor cubed."] },
      { heading: "Check the area unit", paragraphs: ["Square feet (ft²) and feet (ft) measure different things. Floor area is normally reported in square units, while the sides of a room are reported in length units.", "A unit conversion does not account for wall thickness, irregular room shape or the measurement method used to obtain the original area."] },
      { heading: "Use the area converter", paragraphs: ["The linked converter opens with 500 ft² as its input and m² as the target. Confirm the unit pair, then press Convert to reveal the result."] },
    ],
    table: { caption: "Illustrative area conversions", columns: ["Square feet", "Square meters"], rows: [["100", "9.290304"], ["250", "23.22576"], ["500", "46.45152"], ["1,000", "92.90304"]] },
    toolHref: internalHref("/tools/units", { category: "area", from: "ft2", to: "m2", value: "500" }),
    toolLabel: "Open square-feet converter",
    related: ["meters-to-feet", "liters-to-us-gallons"],
  },
  {
    slug: "understanding-inflation-rate",
    title: "How to Read an Inflation Rate — % Change vs Price Level",
    description: "Understand what an annual consumer-price inflation figure represents, how percentage change is calculated and why a reported rate is not a personal cost-of-living estimate.",
    category: "Reference information",
    formula: "rate (%) = (current index − prior index) ÷ prior index × 100",
    takeaway: "An inflation rate describes a change in an index over a stated period",
    imageAlt: "Inflation formula comparing two price-index values over a stated time period.",
    intro: "An annual inflation rate usually describes the percentage change in a consumer-price index over a year. It is a rate of change in an index—not the price level itself, and not necessarily the change experienced by any one household.",
    sections: [
      { heading: "Read the period and measure", paragraphs: ["Check whether a published value is year-over-year, month-over-month, annual average or another measure. Two percentages can only be compared meaningfully when their definitions and periods match.", "A positive annual rate generally means the measured price index is higher than in the comparison period. A lower positive rate can mean prices are still rising, but more slowly."] },
      { heading: "A simple index example", paragraphs: ["If an illustrative index moves from 200 to 206 over a year, the percentage change is (206 − 200) ÷ 200 × 100 = 3%. The 3% describes the index change over that period; it does not mean every item or household spending pattern increased by exactly 3%.", "The index, reference period, collection methods and revisions matter. Always read those alongside the percentage."] },
      { heading: "Explore a selected indicator", paragraphs: ["The linked viewer opens the inflation measure for a selected economy. Choose another economy if needed and press Show to reveal the latest available observation and the historical values.", "Public economic observations may be annual, released after the measured period and revised later. The most recent available year may not be the current year."] },
    ],
    table: { caption: "Illustrative percentage-change calculation", columns: ["Prior index", "Current index", "Change"], rows: [["200", "206", "3%"], ["250", "255", "2%"], ["100", "100", "0%"]] },
    toolHref: internalHref("/tools/economy", { country: "USA", indicator: "inflation" }),
    toolLabel: "Open the inflation indicator",
    related: ["exchange-rate-reference-values", "compound-interest"],
  },
  {
    slug: "split-a-bill-with-tip",
    title: "How to Split a Bill with a Percentage Tip",
    description: "Calculate an even per-person share after adding a percentage tip. Check what the formula includes and use a prefilled, editable example.",
    category: "Calculation methods",
    formula: "share = bill × (1 + tip rate) ÷ people",
    takeaway: "184.50 with a 12% tip for 5 people = 41.328 each",
    imageAlt: "A bill amount, percentage tip and number of people combine to give an even per-person share.",
    intro: "To divide a bill and a proportional tip evenly, first multiply the bill by one plus the tip rate, then divide the total by the number of people. Write the percentage as a decimal: 12% becomes 0.12.",
    sections: [
      { heading: "Work through the example", paragraphs: ["For a bill of 184.50, a 12% tip and 5 people, compute 184.50 × (1 + 0.12) ÷ 5 = 41.328 per person. Rounding to cents gives 41.33 each, but that rounded split totals 206.65 while the unrounded total is 206.64; groups may choose how to handle the extra cent.", "For an even split of the bill before the tip, the tip arrangement is different. Make sure the chosen method reflects the agreement among the people paying."] },
      { heading: "State what the bill includes", paragraphs: ["The example applies the tip rate to the bill value entered. It does not determine whether tax, service charges, discounts or delivery fees should be included; those depend on the receipt and the group’s choice.", "The formula assumes a positive number of people. Check the inputs and rounding rule before using the result to settle a payment."] },
      { heading: "Open the editable example", paragraphs: ["The link opens the formula tool with the example name, expression and values filled in. Press Evaluate to reveal the result. You can change the bill, rate or number of people, then confirm again."] },
    ],
    table: { caption: "Illustrative equal split before currency rounding", columns: ["Bill", "Tip rate", "People", "Share each"], rows: [["184.50", "12%", "5", "41.328"], ["90.00", "15%", "3", "34.50"], ["120.00", "10%", "4", "33.00"]] },
    toolHref: presetHref("tip-split"),
    toolLabel: "Open the bill-splitting example",
    related: ["compound-interest", "solve-linear-systems"],
  },
];

export const guidePath = (guide: Pick<Guide, "slug">) => `/guides/${guide.slug}`;
export function findGuide(slug: string) { return GUIDES.find((guide) => guide.slug === slug); }
